// ============================================================
// Versões fáceis das perguntas NOVAS das atitudes (pares 1 a 3, em
// perguntasNovasAtitudes.ts). Ver perguntasFaceis.ts: «simples» para as
// medidas seletivas, «muitoSimples» para as medidas adicionais.
// ============================================================
import type { VersoesFaceis } from './perguntasFaceis';

type R4 = [string, string, string, string];
const f = (ps: string, rs: R4, ns: string | undefined, pm: string, rm: R4, nm?: string): VersoesFaceis => ({
  simples: { pergunta: ps, respostas: rs, ...(ns ? { naoAconteceu: ns } : {}) },
  muitoSimples: { pergunta: pm, respostas: rm, ...(nm ? { naoAconteceu: nm } : {}) },
});

export const FACEIS_NOVAS: Record<string, VersoesFaceis> = {
  // ── ATI-001 Responsabilidade ──
  'ATI-001|1|0': f('Hoje, estragaste ou partiste alguma coisa. O que fizeste?', ['Não disse nada.', 'Só disse quando viram.', 'Avisei logo.', 'Avisei e ajudei a resolver.'], 'Não estraguei nada.',
    'Partiste alguma coisa?', ['Escondi.', 'Disse quando viram.', 'Avisei.', 'Avisei e ajudei.'], 'Não parti.'),
  'ATI-001|1|1': f('Hoje, fizeste o que combinaste?', ['Não.', 'Só uma parte.', 'Sim, tudo.', 'Sim, e avisei quando acabei.'], undefined,
    'Fizeste o combinado?', ['Não.', 'Uma parte.', 'Sim.', 'Sim, e avisei.']),
  'ATI-001|2|0': f('Hoje, o professor chamou-te a atenção. O que fizeste?', ['Respondi mal.', 'Ouvi, mas fiz igual.', 'Ouvi e corrigi.', 'Corrigi e perguntei como melhorar.'], 'Não me chamou a atenção.',
    'Chamaram-te a atenção. E tu?', ['Respondi mal.', 'Fiz igual.', 'Corrigi.', 'Corrigi e perguntei.'], 'Não chamaram.'),
  'ATI-001|2|1': f('Hoje, deixaste o teu lugar arrumado?', ['Não.', 'Só quando mandaram.', 'Sim, sozinho/a.', 'Sim, e ajudei a equipa.'], undefined,
    'Arrumaste o teu lugar?', ['Não.', 'Quando mandaram.', 'Sim.', 'Sim, e ajudei.']),
  'ATI-001|3|0': f('Hoje, enganaste-te num passo. O que fizeste?', ['Continuei.', 'Não disse a ninguém.', 'Disse e corrigi.', 'Corrigi e anotei.'], 'Não me enganei.',
    'Enganaste-te. E tu?', ['Continuei.', 'Calei-me.', 'Corrigi.', 'Corrigi e anotei.'], 'Não me enganei.'),
  'ATI-001|3|1': f('Hoje, começaste a horas?', ['Não, atrasei os outros.', 'Tarde, mas recuperei.', 'Sim.', 'Sim, e com tudo pronto.'], undefined,
    'Começaste a horas?', ['Não.', 'Um pouco tarde.', 'Sim.', 'Sim, pronto.']),
  // ── ATI-003 Apresentação pessoal ──
  'ATI-003|1|0': f('Hoje, a farda sujou-se. O que fizeste?', ['Continuei assim.', 'Limpei à pressa.', 'Troquei o avental ou o pano.', 'Troquei e avisei um colega.'], 'Não se sujou.',
    'A farda sujou-se?', ['Fiquei assim.', 'Limpei à pressa.', 'Troquei.', 'Troquei e avisei.'], 'Não se sujou.'),
  'ATI-003|1|1': f('Hoje, as unhas e o cabelo estavam bem?', ['Não, unhas compridas ou anéis.', 'Quase.', 'Sim, curtas e cabelo preso.', 'Sim, e lembrei um colega.'], undefined,
    'Unhas e cabelo bem?', ['Não.', 'Quase.', 'Sim.', 'Sim, e ajudei.']),
  'ATI-003|2|0': f('Hoje, saíste da cozinha. Lavaste as mãos ao voltar?', ['Não.', 'Esqueci-me de lavar.', 'Sim, e tirei o avental.', 'Sim, e lembrei um colega.'], 'Não saí.',
    'Lavaste as mãos ao voltar?', ['Não.', 'Esqueci-me.', 'Sim.', 'Sim, e lembrei.'], 'Não saí.'),
  'ATI-003|2|1': f('Hoje, o teu calçado estava certo?', ['Não.', 'Sim, mas sujo.', 'Sim, limpo.', 'Sim, e lembrei quem não trazia.'], undefined,
    'Calçado certo?', ['Não.', 'Sujo.', 'Sim.', 'Sim, e lembrei.']),
  'ATI-003|3|0': f('Hoje, falaste com alguém de fora. Como estavas?', ['Desarrumado.', 'Arrumado, mas mal sentado ou encostado.', 'Arrumado e direito.', 'Arrumado, direito e simpático.'], 'Não falei com ninguém de fora.',
    'Alguém de fora. Estavas bem?', ['Não.', 'Mais ou menos.', 'Sim.', 'Sim, e simpático.'], 'Não houve.'),
  'ATI-003|3|1': f('Hoje, verificaste a farda antes de entrar?', ['Não.', 'Só a touca.', 'Sim, tudo.', 'Sim, e ajudei um colega.'], undefined,
    'Viste a farda antes?', ['Não.', 'Só a touca.', 'Sim.', 'Sim, e ajudei.']),
  // ── ATI-005 Autocontrolo ──
  'ATI-005|1|0': f('Hoje, um colega disse uma coisa de que não gostaste. O que fizeste?', ['Respondi mal.', 'Amuei.', 'Respondi com calma.', 'Respondi com calma e resolvemos.'], 'Ninguém me disse nada.',
    'Disseram-te uma coisa má. E tu?', ['Respondi mal.', 'Amuei.', 'Fiquei calmo.', 'Resolvemos.'], 'Não disseram.'),
  'ATI-005|1|1': f('Hoje, tiveste de esperar. Como foi?', ['Passei à frente.', 'Esperei a reclamar.', 'Esperei com calma.', 'Esperei e adiantei outra coisa.'], undefined,
    'Esperaste a tua vez?', ['Não.', 'A reclamar.', 'Sim.', 'Sim, e adiantei.']),
  'ATI-005|2|0': f('Hoje, o prato correu mal. O que fizeste?', ['Atirei coisas ou disse asneiras.', 'Fiquei irritado.', 'Respirei e tentei outra vez.', 'Tentei outra vez e fiquei bem-disposto.'], 'Não correu mal.',
    'Correu mal. E tu?', ['Irritei-me muito.', 'Irritei-me.', 'Tentei outra vez.', 'Tentei e sorri.'], 'Correu bem.'),
  'ATI-005|2|1': f('Hoje, o professor deu-te uma indicação. Como reagiste?', ['Respondi mal.', 'Fiz a reclamar.', 'Fiz com calma.', 'Fiz e agradeci.'], undefined,
    'O professor pediu. E tu?', ['Respondi mal.', 'Reclamei.', 'Fiz.', 'Fiz e agradeci.']),
  'ATI-005|3|0': f('Hoje, houve barulho na cozinha. O que fizeste?', ['Gritei também.', 'Fiquei nervoso.', 'Continuei concentrado.', 'Continuei e ajudei a acalmar.'], 'Não houve barulho.',
    'Houve barulho. E tu?', ['Gritei.', 'Fiquei nervoso.', 'Continuei.', 'Acalmei os outros.'], 'Não houve.'),
  'ATI-005|3|1': f('Hoje, usaste o telemóvel sem autorização?', ['Sim, várias vezes.', 'Sim, uma vez.', 'Não.', 'Não, e lembrei um colega.'], undefined,
    'Usaste o telemóvel?', ['Muitas vezes.', 'Uma vez.', 'Não.', 'Não, e lembrei.']),
  // ── ATI-011 Organização ──
  'ATI-011|1|0': f('Hoje, antes de cozinhar, o que fizeste?', ['Comecei logo.', 'Li a ficha à pressa.', 'Li e separei tudo.', 'Li, separei e combinei com a equipa.'], 'Não cozinhei.',
    'Antes de cozinhar, leste a ficha?', ['Não.', 'À pressa.', 'Sim, e separei.', 'Sim, e combinei.'], 'Não cozinhei.'),
  'ATI-011|1|1': f('Hoje, acabaste a tempo?', ['Não.', 'À pressa.', 'Sim, bem.', 'Sim, e arrumei com calma.'], undefined,
    'Acabaste a tempo?', ['Não.', 'À pressa.', 'Sim.', 'Sim, com calma.']),
  'ATI-011|2|0': f('Hoje, foste lavando a loiça?', ['Não, deixei acumular.', 'Só no fim.', 'Sim, enquanto trabalhava.', 'Sim, e ajudei outra bancada.'], 'Não usei loiça.',
    'Lavaste a loiça logo?', ['Não.', 'No fim.', 'Sim.', 'Sim, e ajudei.'], 'Não usei.'),
  'ATI-011|2|1': f('Hoje, registaste o que era pedido?', ['Não.', 'Só uma parte.', 'Sim, tudo.', 'Sim, e escrevi o que aprendi.'], undefined,
    'Escreveste o pedido?', ['Não.', 'Uma parte.', 'Sim.', 'Sim, e mais.']),
  'ATI-011|3|0': f('Hoje, faltou uma coisa. O que fizeste?', ['Fiquei parado.', 'Andei às voltas.', 'Pedi e fiz outra tarefa.', 'Pedi, fiz outra tarefa e avisei.'], 'Não faltou nada.',
    'Faltou uma coisa. E tu?', ['Parei.', 'Andei às voltas.', 'Pedi.', 'Pedi e avisei.'], 'Não faltou.'),
  'ATI-011|3|1': f('Hoje, guardaste a comida com rótulo e data?', ['Não.', 'Guardei sem rótulo.', 'Sim.', 'Sim, e vi os prazos.'], undefined,
    'Puseste rótulo?', ['Não.', 'Sem rótulo.', 'Sim.', 'Sim, e vi prazos.']),
  // ── ATI-013 Disponibilidade para aprender ──
  'ATI-013|1|0': f('Hoje, não percebeste uma explicação. O que fizeste?', ['Fiquei calado.', 'Perguntei a um colega.', 'Perguntei ao professor.', 'Perguntei e expliquei a outro.'], 'Percebi tudo.',
    'Não percebeste. E tu?', ['Calei-me.', 'Perguntei a um colega.', 'Perguntei ao professor.', 'Expliquei a outro.'], 'Percebi.'),
  'ATI-013|1|1': f('Hoje, viste a demonstração do professor?', ['Não, estava distraído.', 'Só uma parte.', 'Sim, toda.', 'Sim, e fiz perguntas.'], undefined,
    'Viste o professor fazer?', ['Não.', 'Um pouco.', 'Sim.', 'Sim, e perguntei.']),
  'ATI-013|2|0': f('Hoje, aprendeste uma técnica nova. O que fizeste?', ['Não quis experimentar.', 'Experimentei uma vez.', 'Experimentei até sair razoável.', 'Experimentei até sair bem.'], 'Não aprendi técnica nova.',
    'Técnica nova. Experimentaste?', ['Não.', 'Uma vez.', 'Sim.', 'Até sair bem.'], 'Não houve.'),
  'ATI-013|2|1': f('Hoje, leste a matéria?', ['Não.', 'À pressa.', 'Sim, com atenção.', 'Sim, e procurei mais.'], undefined,
    'Leste a matéria?', ['Não.', 'À pressa.', 'Sim.', 'Sim, e mais.']),
  'ATI-013|3|0': f('Hoje, um colega mostrou-te uma maneira melhor. O que fizeste?', ['Não liguei.', 'Fiz à minha maneira.', 'Experimentei.', 'Experimentei e agradeci.'], 'Ninguém me mostrou.',
    'Um colega ensinou-te. E tu?', ['Não liguei.', 'Fiz igual.', 'Experimentei.', 'Agradeci.'], 'Não houve.'),
  'ATI-013|3|1': f('Hoje, sabes dizer o que aprendeste?', ['Não.', 'Uma coisa, mas não sei explicar.', 'Sim.', 'Sim, e onde vou usar.'], undefined,
    'O que aprendeste?', ['Não sei.', 'Uma coisa.', 'Sei dizer.', 'Sei e onde usar.']),
  // ── ATI-015 Regras ──
  'ATI-015|1|0': f('Hoje, houve uma regra nova. Cumpriste?', ['Não.', 'Só quando viam.', 'Sim, sempre.', 'Sim, e lembrei outros.'], 'Não houve regra nova.',
    'Regra nova. Cumpriste?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, e lembrei.'], 'Não houve.'),
  'ATI-015|1|1': f('Hoje, cumpriste as horas?', ['Não, atrasei-me.', 'Atrasei-me um pouco.', 'Sim.', 'Sim, e estava pronto antes.'], undefined,
    'Chegaste a horas?', ['Não.', 'Quase.', 'Sim.', 'Sim, antes.']),
  'ATI-015|2|0': f('Hoje, um colega não cumpriu uma regra. O que fizeste?', ['Fiz igual.', 'Nada.', 'Lembrei-o com calma.', 'Lembrei-o e expliquei porquê.'], 'Todos cumpriram.',
    'Colega falhou a regra. E tu?', ['Fiz igual.', 'Nada.', 'Lembrei-o.', 'Expliquei porquê.'], 'Todos cumpriram.'),
  'ATI-015|2|1': f('Hoje, devolveste o material ao sítio?', ['Não, usei mal.', 'Não devolvi.', 'Sim.', 'Sim, e avisei se estava estragado.'], undefined,
    'Devolveste o material?', ['Não.', 'Esqueci-me.', 'Sim.', 'Sim, e avisei.']),
  'ATI-015|3|0': f('Hoje, não concordaste com uma regra. O que fizeste?', ['Não cumpri.', 'Cumpri a reclamar.', 'Cumpri e perguntei porquê.', 'Perguntei com respeito e percebi.'], 'Concordei com todas.',
    'Não gostaste da regra. E tu?', ['Não cumpri.', 'Reclamei.', 'Cumpri.', 'Perguntei porquê.'], 'Concordei.'),
  'ATI-015|3|1': f('Hoje, seguiste a ficha?', ['Não.', 'Só uma parte.', 'Sim.', 'Sim, e perguntei antes de mudar.'], undefined,
    'Seguiste a ficha?', ['Não.', 'Uma parte.', 'Sim.', 'Sim, toda.']),
  // ── ATI-016 Higiene alimentar ──
  'ATI-016|1|0': f('Hoje, passaste do cru para o cozinhado. Trocaste a tábua e a faca?', ['Não.', 'Só limpei por cima.', 'Sim.', 'Sim, e avisei um colega.'], 'Não mexi em cru.',
    'Trocaste a tábua?', ['Não.', 'Limpei por cima.', 'Sim.', 'Sim, e avisei.'], 'Não mexi.'),
  'ATI-016|1|1': f('Hoje, guardaste logo no frio o que precisava de frio?', ['Não.', 'Tarde.', 'Sim, logo.', 'Sim, e vi a temperatura.'], undefined,
    'Guardaste no frio?', ['Não.', 'Tarde.', 'Sim.', 'Sim, e vi.']),
  'ATI-016|2|0': f('Hoje, como provaste a comida?', ['Com os dedos.', 'Com colher, mas voltei a pô-la na panela.', 'Com uma colher limpa de cada vez.', 'Assim, e lembrei os colegas.'], 'Não provei.',
    'Provaste com colher limpa?', ['Com os dedos.', 'Com a mesma colher.', 'Sim.', 'Sim, e lembrei.'], 'Não provei.'),
  'ATI-016|2|1': f('Hoje, usaste panos diferentes para limpar e secar?', ['Não.', 'Só troquei no fim.', 'Sim.', 'Sim, e troquei quando sujaram.'], undefined,
    'Panos diferentes?', ['Não.', 'No fim.', 'Sim.', 'Sim, e troquei.']),
  'ATI-016|3|0': f('Hoje, caiu comida ao chão. O que fizeste?', ['Usei na mesma.', 'Lavei e usei.', 'Deitei fora e avisei.', 'Deitei fora, avisei e registei.'], 'Não caiu nada.',
    'Caiu comida. E tu?', ['Usei.', 'Lavei e usei.', 'Deitei fora.', 'Deitei fora e avisei.'], 'Não caiu.'),
  'ATI-016|3|1': f('Hoje, lavaste as mãos com sabão?', ['Não.', 'Só com água.', 'Sim, com sabão.', 'Sim, e outra vez depois do lixo.'], undefined,
    'Lavaste com sabão?', ['Não.', 'Só água.', 'Sim.', 'Sim, várias vezes.']),
  // ── ATI-017 Segurança ──
  'ATI-017|1|0': f('Hoje, andaste com uma faca. Como?', ['Com a ponta para a frente.', 'Com cuidado, sem avisar.', 'Com a ponta para baixo.', 'Ponta para baixo e avisei «faca!».'], 'Não andei com facas.',
    'Andaste com a faca bem?', ['Não.', 'Sem avisar.', 'Sim.', 'Sim, e avisei.'], 'Não andei.'),
  'ATI-017|1|1': f('Hoje, usaste pegas no que estava quente?', ['Não.', 'Sim, sem avisar.', 'Sim, e avisei «quente!».', 'Sim, avisei e virei os cabos.'], undefined,
    'Usaste pegas?', ['Não.', 'Sem avisar.', 'Sim.', 'Sim, e avisei.']),
  'ATI-017|2|0': f('Hoje, caiu água ou gordura no chão. O que fizeste?', ['Deixei.', 'Avisei, mas não limpei.', 'Limpei logo.', 'Limpei e avisei.'], 'Não caiu.',
    'Chão molhado. E tu?', ['Deixei.', 'Avisei.', 'Limpei.', 'Limpei e avisei.'], 'Não caiu.'),
  'ATI-017|2|1': f('Hoje, levantaste pesos com cuidado?', ['Não, dobrei as costas.', 'Às vezes.', 'Sim, dobrei os joelhos.', 'Sim, e ajudei um colega.'], undefined,
    'Pesos com cuidado?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, e ajudei.']),
  'ATI-017|3|0': f('Hoje, usaste uma máquina. Como?', ['Sem saber usar.', 'Com a mão perto da lâmina.', 'Como o professor ensinou.', 'Como ensinado, e desliguei para limpar.'], 'Não usei máquinas.',
    'Usaste bem a máquina?', ['Não.', 'Com perigo.', 'Sim.', 'Sim, e desliguei.'], 'Não usei.'),
  'ATI-017|3|1': f('Hoje, deixaste as passagens livres?', ['Não.', 'Tirei depois.', 'Sim.', 'Sim, e tirei o de outros.'], undefined,
    'Passagens livres?', ['Não.', 'Depois.', 'Sim.', 'Sim, e ajudei.']),
  // ── ATI-002 Autonomia ──
  'ATI-002|1|0': f('Hoje, acabaste a tarefa. E depois?', ['Fiquei parado.', 'Perguntei o que fazer.', 'Vi a ficha e continuei.', 'Continuei e ajudei.'], 'Não acabei antes.',
    'Acabaste. E depois?', ['Parei.', 'Perguntei.', 'Continuei.', 'Ajudei.'], 'Não acabei.'),
  'ATI-002|1|1': f('Hoje, precisaste muito do professor?', ['Em cada passo.', 'Várias vezes.', 'Só uma vez.', 'Não, só mostrei no fim.'], undefined,
    'Precisaste do professor?', ['Muito.', 'Algumas vezes.', 'Uma vez.', 'Não.']),
  'ATI-002|2|0': f('Hoje, tiveste uma dúvida. O que fizeste primeiro?', ['Perguntei logo.', 'Perguntei a um colega.', 'Vi na ficha.', 'Vi na ficha e resolvi.'], 'Não tive dúvidas.',
    'Dúvida. Onde viste primeiro?', ['Perguntei logo.', 'A um colega.', 'Na ficha.', 'Na ficha e resolvi.'], 'Não tive.'),
  'ATI-002|2|1': f('Hoje, fizeste a tua parte sozinho/a?', ['Não, fizeram por mim.', 'Com muita ajuda.', 'Sim.', 'Sim, e confirmei.'], undefined,
    'Fizeste sozinho/a?', ['Não.', 'Com ajuda.', 'Sim.', 'Sim, e confirmei.']),
  'ATI-002|3|0': f('Hoje, faltou alguma coisa. O que fizeste?', ['Esperei.', 'Fui pedir sem saber o quê.', 'Pedi o que faltava.', 'Resolvi e avisei a equipa.'], 'Não faltou.',
    'Faltou uma coisa. E tu?', ['Esperei.', 'Fui pedir.', 'Pedi certo.', 'Resolvi.'], 'Não faltou.'),
  'ATI-002|3|1': f('Hoje, cumpriste os tempos?', ['Não pensei nisso.', 'Atrasei-me.', 'Sim.', 'Sim, e adiantei.'], undefined,
    'Cumpriste o tempo?', ['Não.', 'Atrasei.', 'Sim.', 'Sim, e adiantei.']),
  // ── ATI-007 Empatia ──
  'ATI-007|1|0': f('Hoje, um colega teve dificuldade. O que fizeste?', ['Ri-me.', 'Não liguei.', 'Perguntei se precisava.', 'Ajudei sem o envergonhar.'], 'Ninguém teve dificuldade.',
    'Colega com dificuldade. E tu?', ['Ri-me.', 'Nada.', 'Perguntei.', 'Ajudei.'], 'Não houve.'),
  'ATI-007|1|1': f('Hoje, falaste bem com todos?', ['Não, falei mal.', 'Com uns sim, com outros não.', 'Sim, com todos.', 'Sim, e incluí quem estava calado.'], undefined,
    'Falaste bem com todos?', ['Não.', 'Com alguns.', 'Sim.', 'Sim, e incluí.']),
  'ATI-007|2|0': f('Hoje, um colega estava triste ou cansado. O que fizeste?', ['Não reparei.', 'Nada.', 'Perguntei se estava bem.', 'Ajudei-o.'], 'Não vi ninguém assim.',
    'Colega triste. E tu?', ['Não vi.', 'Nada.', 'Perguntei.', 'Ajudei.'], 'Não vi.'),
  'ATI-007|2|1': f('Hoje, pensaste em quem vai comer?', ['Não.', 'Pensei, mas não mudou nada.', 'Sim, tive cuidado.', 'Sim, e perguntei por alergias.'], undefined,
    'Pensaste em quem come?', ['Não.', 'Um pouco.', 'Sim.', 'Sim, e perguntei.']),
  'ATI-007|3|0': f('Hoje, um colega enganou-se à frente de todos. O que fizeste?', ['Ri-me.', 'Fiquei a olhar.', 'Ajudei em silêncio.', 'Ajudei e disse que acontece a todos.'], 'Ninguém se enganou.',
    'Colega enganou-se. E tu?', ['Ri-me.', 'Olhei.', 'Ajudei.', 'Ajudei e animei.'], 'Não houve.'),
  'ATI-007|3|1': f('Hoje, deixaste limpo para quem limpa?', ['Não.', 'Só uma parte.', 'Sim, o meu.', 'Sim, e agradeci.'], undefined,
    'Deixaste limpo?', ['Não.', 'Uma parte.', 'Sim.', 'Sim, e agradeci.']),
  // ── ATI-008 Escuta ativa ──
  'ATI-008|1|0': f('Hoje, um colega deu uma ideia. O que fizeste?', ['Interrompi.', 'Ouvi distraído.', 'Ouvi até ao fim.', 'Ouvi e perguntei.'], 'Ninguém deu ideias.',
    'Colega deu ideia. Ouviste?', ['Não.', 'Distraído.', 'Sim.', 'Sim, e perguntei.'], 'Não houve.'),
  'ATI-008|1|1': f('Hoje, ouviste o professor?', ['Não, falei por cima.', 'Só uma parte.', 'Sim, tudo.', 'Sim, e lembro-me do importante.'], undefined,
    'Ouviste o professor?', ['Não.', 'Um pouco.', 'Sim.', 'Sim, tudo.']),
  'ATI-008|2|0': f('Hoje, não concordaste com um colega. Ouviste-o?', ['Não, interrompi.', 'Deixei falar, mas não ouvi.', 'Ouvi e depois falei.', 'Ouvi, confirmei e respondi.'], 'Não discordei.',
    'Discordaste. Ouviste primeiro?', ['Não.', 'Mais ou menos.', 'Sim.', 'Sim, e confirmei.'], 'Não discordei.'),
  'ATI-008|2|1': f('Hoje, consegues repetir a explicação?', ['Não.', 'Só uma parte.', 'Sim, o principal.', 'Sim, e expliquei a um colega.'], undefined,
    'Sabes repetir?', ['Não.', 'Um pouco.', 'Sim.', 'Sim, e expliquei.']),
  'ATI-008|3|0': f('Hoje, alguém da equipa falou de um problema. O que fizeste?', ['Mudei de assunto.', 'Ouvi calado.', 'Ouvi e perguntei.', 'Ouvi e ajudei a resolver.'], 'Ninguém falou disso.',
    'Problema na equipa. E tu?', ['Mudei de assunto.', 'Calei-me.', 'Perguntei.', 'Ajudei.'], 'Não houve.'),
  'ATI-008|3|1': f('Hoje, ouviste os avisos («quente!», «faca!»)?', ['Não.', 'Reagi tarde.', 'Sim, logo.', 'Sim, e passei o aviso.'], undefined,
    'Ouviste os avisos?', ['Não.', 'Tarde.', 'Sim.', 'Sim, e passei.']),
  // ── ATI-009 Cooperação ──
  'ATI-009|1|0': f('Hoje, um colega atrasou-se. O que fizeste?', ['Deixei-o sozinho.', 'Reclamei.', 'Ajudei depois do meu.', 'Ajudei e combinámos.'], 'Ninguém se atrasou.',
    'Colega atrasado. E tu?', ['Nada.', 'Reclamei.', 'Ajudei.', 'Ajudei e combinámos.'], 'Não houve.'),
  'ATI-009|1|1': f('Hoje, dividiram bem as tarefas?', ['Fiquei com o mais fácil.', 'Aceitei sem dizer nada.', 'Ajudei a dividir.', 'Ajudei e fiquei com o difícil.'], undefined,
    'Dividiram bem?', ['Fiquei com o fácil.', 'Calei-me.', 'Ajudei.', 'Fiquei com o difícil.']),
  'ATI-009|2|0': f('Hoje, a equipa decidiu uma coisa. O que fizeste?', ['Decidi sozinho/a.', 'Não dei opinião.', 'Dei opinião e aceitei.', 'Ajudei a chegar a acordo.'], 'Não decidimos nada.',
    'Decidiram. E tu?', ['Decidi sozinho/a.', 'Calei-me.', 'Dei opinião.', 'Ajudei no acordo.'], 'Não houve.'),
  'ATI-009|2|1': f('Hoje, partilhaste o material?', ['Não.', 'Quando pediram.', 'Sem pedirem.', 'Sim, e organizei para todos.'], undefined,
    'Partilhaste?', ['Não.', 'Quando pediram.', 'Sim.', 'Sim, para todos.']),
  'ATI-009|3|0': f('Hoje, a equipa teve um problema. O que fizeste?', ['Culpei alguém.', 'Fiquei de fora.', 'Ajudei a resolver.', 'Ajudei sem culpar ninguém.'], 'Não houve problemas.',
    'Problema na equipa. E tu?', ['Culpei.', 'Fiquei de fora.', 'Ajudei.', 'Ajudei bem.'], 'Não houve.'),
  'ATI-009|3|1': f('Hoje, ficaste até a equipa acabar?', ['Não, saí.', 'Ajudei um bocado.', 'Sim.', 'Sim, e ajudei outra equipa.'], undefined,
    'Ficaste até ao fim?', ['Não.', 'Um pouco.', 'Sim.', 'Sim, e mais.']),
  // ── ATI-010 Empenho ──
  'ATI-010|1|0': f('Hoje, não te saiu bem à primeira. O que fizeste?', ['Desisti.', 'Pedi a outro.', 'Tentei outra vez.', 'Tentei até sair bem.'], 'Saiu bem à primeira.',
    'Não saiu bem. E tu?', ['Desisti.', 'Pedi a outro.', 'Tentei.', 'Até sair bem.'], 'Saiu bem.'),
  'ATI-010|1|1': f('Hoje, fizeste as tarefas chatas?', ['Fugi delas.', 'À pressa.', 'Sim, bem.', 'Sim, sem reclamar.'], undefined,
    'Fizeste as tarefas chatas?', ['Não.', 'À pressa.', 'Sim.', 'Sim, sem reclamar.']),
  'ATI-010|2|0': f('Hoje, o prato não ficou como na ficha. O que fizeste?', ['Entreguei assim.', 'Disfarcei.', 'Perguntei e corrigi.', 'Corrigi e anotei.'], 'Ficou como na ficha.',
    'Prato diferente. E tu?', ['Entreguei.', 'Disfarcei.', 'Corrigi.', 'Corrigi e anotei.'], 'Ficou bem.'),
  'ATI-010|2|1': f('Hoje, trabalhaste a sério quanto tempo?', ['Pouco.', 'Metade.', 'Quase tudo.', 'Tudo, e adiantei.'], undefined,
    'Trabalhaste muito?', ['Pouco.', 'Metade.', 'Quase tudo.', 'Tudo.']),
  'ATI-010|3|0': f('Hoje, pediram-te para repetir. O que fizeste?', ['Recusei.', 'Repeti a reclamar.', 'Repeti com atenção.', 'Repeti e pedi para ver.'], 'Não repeti nada.',
    'Repetiste?', ['Não.', 'A reclamar.', 'Sim.', 'Sim, e pedi para ver.'], 'Não foi preciso.'),
  'ATI-010|3|1': f('Hoje, estavas cansado. O que fizeste?', ['Parei.', 'Abrandei muito.', 'Continuei.', 'Continuei e animei a equipa.'], undefined,
    'Cansado. Continuaste?', ['Parei.', 'Devagar.', 'Sim.', 'Sim, e animei.']),
  // ── ATI-012 Flexibilidade ──
  'ATI-012|1|0': f('Hoje, o professor mudou o plano. O que fizeste?', ['Reclamei.', 'Mudei a reclamar.', 'Mudei sem problema.', 'Mudei e ajudei os outros.'], 'O plano não mudou.',
    'Mudou o plano. E tu?', ['Reclamei.', 'Mudei a reclamar.', 'Mudei.', 'Ajudei.'], 'Não mudou.'),
  'ATI-012|1|1': f('Hoje, fizeste uma tarefa que não querias?', ['Recusei.', 'Fiz mal.', 'Fiz bem.', 'Fiz bem e aprendi.'], undefined,
    'Tarefa que não querias?', ['Recusei.', 'Fiz mal.', 'Fiz bem.', 'Aprendi.']),
  'ATI-012|2|0': f('Hoje, trabalhaste com um colega que não escolheste. Como foi?', ['Recusei.', 'Falei pouco.', 'Trabalhei bem.', 'Trabalhei bem e conheci-o.'], 'Escolhi com quem.',
    'Colega que não escolheste?', ['Recusei.', 'Falei pouco.', 'Correu bem.', 'Ficámos amigos.'], 'Escolhi.'),
  'ATI-012|2|1': f('Hoje, alguém fez de maneira diferente. O que fizeste?', ['Disse que estava mal.', 'Fiquei incomodado.', 'Aceitei.', 'Aceitei e experimentei.'], undefined,
    'Maneira diferente. E tu?', ['Disse que estava mal.', 'Incomodou-me.', 'Aceitei.', 'Experimentei.']),
  'ATI-012|3|0': f('Hoje, foi preciso trocar um ingrediente. O que fizeste?', ['Não quis.', 'Fiz mal.', 'Troquei como disseram.', 'Troquei e dei uma ideia.'], 'Não foi preciso.',
    'Trocar ingrediente. E tu?', ['Não quis.', 'Fiz mal.', 'Troquei.', 'Dei uma ideia.'], 'Não foi preciso.'),
  'ATI-012|3|1': f('Hoje, fizeste uma função nova?', ['Não quis.', 'Fiz pouco.', 'Fiz.', 'Fiz e ajudei a equipa.'], undefined,
    'Função nova?', ['Não quis.', 'Pouco.', 'Fiz.', 'Fiz e ajudei.']),
  // ── ATI-018 Bem-estar dos outros ──
  'ATI-018|1|0': f('Hoje, fizeste piadas. Como foram?', ['Gozei com alguém.', 'Uma pode ter ofendido.', 'Não ofenderam ninguém.', 'Não ofenderam e parei a tempo.'], 'Não fiz piadas.',
    'Piadas. Ofendeste alguém?', ['Sim.', 'Talvez.', 'Não.', 'Não, e parei a tempo.'], 'Não fiz.'),
  'ATI-018|1|1': f('Hoje, respeitaste o espaço dos outros?', ['Não, empurrei.', 'Às vezes sem licença.', 'Sim, pedi licença.', 'Sim, e arrumei o espaço comum.'], undefined,
    'Pediste licença?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, e arrumei.']),
  'ATI-018|2|0': f('Hoje, um colega foi posto de parte. O que fizeste?', ['Juntei-me aos outros.', 'Nada.', 'Falei com ele.', 'Chamei-o para o meu grupo.'], 'Ninguém foi posto de parte.',
    'Colega de parte. E tu?', ['Juntei-me aos outros.', 'Nada.', 'Falei.', 'Chamei-o.'], 'Não houve.'),
  'ATI-018|2|1': f('Hoje, fizeste muito barulho?', ['Sim, incomodei.', 'Às vezes.', 'Não.', 'Não, e ajudei a baixar.'], undefined,
    'Fizeste barulho?', ['Muito.', 'Às vezes.', 'Não.', 'Não, e ajudei.']),
  'ATI-018|3|0': f('Hoje, pediram-te para parar. O que fizeste?', ['Continuei.', 'Parei a reclamar.', 'Parei logo.', 'Parei e pedi desculpa.'], 'Ninguém pediu.',
    'Pediram para parar?', ['Continuei.', 'Reclamei.', 'Parei.', 'Pedi desculpa.'], 'Não pediram.'),
  'ATI-018|3|1': f('Hoje, mexeste nas coisas dos colegas sem pedir?', ['Sim.', 'Uma vez.', 'Não, pedi sempre.', 'Pedi e devolvi bem.'], undefined,
    'Pediste antes de mexer?', ['Não.', 'Quase sempre.', 'Sim.', 'Sim, e devolvi.']),
  // ── ATI-022 Diferenças ──
  'ATI-022|1|0': f('Hoje, um colega gostava de outra coisa. O que fizeste?', ['Gozei.', 'Ignorei.', 'Respeitei.', 'Respeitei e quis saber mais.'], 'Não houve.',
    'Gosto diferente. E tu?', ['Gozei.', 'Ignorei.', 'Respeitei.', 'Quis saber mais.'], 'Não houve.'),
  'ATI-022|1|1': f('Hoje, trabalhaste bem com colegas de outras culturas?', ['Fiz piadas.', 'Afastei-me.', 'Sim, como com os outros.', 'Sim, e aprendi com eles.'], undefined,
    'Trabalhaste com todos?', ['Gozei.', 'Afastei-me.', 'Sim.', 'Sim, e aprendi.']),
  'ATI-022|2|0': f('Hoje, um colega precisou de mais tempo. O que fizeste?', ['Reclamei.', 'Fiquei impaciente.', 'Esperei.', 'Esperei e ajudei.'], 'Ninguém precisou.',
    'Colega mais lento. E tu?', ['Reclamei.', 'Impaciente.', 'Esperei.', 'Ajudei.'], 'Não houve.'),
  'ATI-022|2|1': f('Hoje, pensaste nas alergias?', ['Não.', 'Pensei, mas não fiz nada.', 'Sim, tive cuidado.', 'Sim, e perguntei.'], undefined,
    'Pensaste nas alergias?', ['Não.', 'Um pouco.', 'Sim.', 'Sim, e perguntei.']),
  'ATI-022|3|0': f('Hoje, alguém falou do seu país ou família. O que fizeste?', ['Disse coisas más.', 'Não liguei.', 'Ouvi com respeito.', 'Ouvi e perguntei.'], 'Ninguém falou.',
    'Falaram da família. E tu?', ['Disse coisas más.', 'Não liguei.', 'Ouvi.', 'Perguntei.'], 'Não falaram.'),
  'ATI-022|3|1': f('Hoje, aceitaste o teu grupo?', ['Recusei alguém.', 'Contrariado.', 'Sim.', 'Sim, e ajudei quem ficou sozinho.'], undefined,
    'Aceitaste o grupo?', ['Não.', 'Contrariado.', 'Sim.', 'Sim, e ajudei.']),
  // ── ATI-004 Iniciativa ──
  'ATI-004|1|0': f('Hoje, viste uma coisa por fazer que não era tua. O que fizeste?', ['Não fiz.', 'Só quando pediram.', 'Fiz sem pedirem.', 'Fiz e avisei a equipa.'], 'Não vi nada.',
    'Coisa por fazer. E tu?', ['Não fiz.', 'Quando pediram.', 'Fiz.', 'Fiz e avisei.'], 'Não vi.'),
  'ATI-004|1|1': f('Hoje, acabaste cedo. O que fizeste?', ['Fui ao telemóvel.', 'Fui conversar.', 'Ajudei uma equipa.', 'Ajudei e pedi mais trabalho.'], undefined,
    'Acabaste cedo. E depois?', ['Telemóvel.', 'Conversa.', 'Ajudei.', 'Pedi mais.']),
  'ATI-004|2|0': f('Hoje, deste uma ideia?', ['Não.', 'Tive, mas não disse.', 'Sim.', 'Sim, e ajudei a fazê-la.'], 'Não tive ideias.',
    'Deste uma ideia?', ['Não.', 'Não disse.', 'Sim.', 'Sim, e fizemos.'], 'Não tive.'),
  'ATI-004|2|1': f('Hoje, preparaste o material antes de pedirem?', ['Não.', 'Uma coisa.', 'O do início.', 'O do início e o seguinte.'], undefined,
    'Preparaste antes?', ['Não.', 'Pouco.', 'Sim.', 'Sim, tudo.']),
  'ATI-004|3|0': f('Hoje, o professor pediu voluntários. O que fizeste?', ['Escondi-me.', 'Esperei por outro.', 'Ofereci-me.', 'Ofereci-me logo e fiz bem.'], 'Não pediu.',
    'Pediram voluntários. E tu?', ['Escondi-me.', 'Esperei.', 'Fui eu.', 'Fui logo.'], 'Não pediram.'),
  'ATI-004|3|1': f('Hoje, um colega não sabia o que fazer. O que fizeste?', ['Nada.', 'Mandei-o perguntar.', 'Expliquei.', 'Expliquei e fiz com ele.'], undefined,
    'Colega perdido. E tu?', ['Nada.', 'Mandei perguntar.', 'Expliquei.', 'Fiz com ele.']),
  // ── ATI-006 Assertividade ──
  'ATI-006|1|0': f('Hoje, não concordaste com uma decisão. O que fizeste?', ['Calei-me chateado.', 'Reclamei com outros.', 'Disse com calma.', 'Disse com calma e expliquei.'], 'Concordei.',
    'Não concordaste. Disseste?', ['Não, amuei.', 'A outros.', 'Sim, com calma.', 'Sim, e expliquei.'], 'Concordei.'),
  'ATI-006|1|1': f('Hoje, como pediste o que precisavas?', ['Gritei.', 'Não pedi.', 'Pedi com educação.', 'Pedi e agradeci.'], undefined,
    'Pediste bem?', ['Gritei.', 'Não pedi.', 'Sim.', 'Sim, e agradeci.']),
  'ATI-006|2|0': f('Hoje, um colega prejudicou-te. O que fizeste?', ['Vinguei-me.', 'Fiquei a remoer.', 'Disse-lhe com calma.', 'Disse e combinámos.'], 'Ninguém me prejudicou.',
    'Prejudicaram-te. E tu?', ['Vinguei-me.', 'Calei-me.', 'Disse com calma.', 'Combinámos.'], 'Não houve.'),
  'ATI-006|2|1': f('Hoje, disseste «não» a um pedido. Como?', ['Disse sim sem querer.', 'Disse não de forma bruta.', 'Disse não com educação.', 'Disse não e dei outra ideia.'], undefined,
    'Disseste «não»?', ['Disse sim sem querer.', 'Bruto.', 'Com educação.', 'Com outra ideia.']),
  'ATI-006|3|0': f('Hoje, a equipa fez uma coisa errada. O que fizeste?', ['Deixei.', 'Disse de forma agressiva.', 'Disse com calma.', 'Disse e propus como fazer.'], 'Não fizeram nada errado.',
    'Equipa errou. Disseste?', ['Não.', 'Zangado.', 'Com calma.', 'E propus.'], 'Não errou.'),
  'ATI-006|3|1': f('Hoje, falaste para a turma?', ['Não, mesmo querendo.', 'Baixinho.', 'Sim, de forma clara.', 'Sim, a olhar para todos.'], undefined,
    'Falaste para a turma?', ['Não.', 'Baixinho.', 'Sim.', 'Sim, bem.']),
  // ── ATI-014 Sustentabilidade ──
  'ATI-014|1|0': f('Hoje, aproveitaste as sobras?', ['Deitei tudo fora.', 'Guardei uma parte.', 'Aproveitei.', 'Aproveitei e dei uma receita.'], 'Não houve sobras.',
    'Aproveitaste sobras?', ['Não.', 'Um pouco.', 'Sim.', 'Sim, e dei ideia.'], 'Não houve.'),
  'ATI-014|1|1': f('Hoje, fechaste torneiras e luzes?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, e as dos outros.'], undefined,
    'Fechaste água e luz?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, todas.']),
  'ATI-014|2|0': f('Hoje, separaste o lixo?', ['Não.', 'Uma parte.', 'Sim, tudo.', 'Sim, e corrigi o dos outros.'], 'Não fiz lixo.',
    'Separaste o lixo?', ['Não.', 'Uma parte.', 'Sim.', 'Sim, e corrigi.'], 'Não fiz lixo.'),
  'ATI-014|2|1': f('Hoje, gastaste película, papel ou luvas a mais?', ['Muito a mais.', 'Um bocado a mais.', 'Só o preciso.', 'Só o preciso e reutilizei.'], undefined,
    'Gastaste a mais?', ['Muito.', 'Um pouco.', 'Não.', 'Não, e reutilizei.']),
  'ATI-014|3|0': f('Hoje, escolheste ingredientes da época?', ['Não pensei.', 'Pensei, mas igual.', 'Sim.', 'Sim, e expliquei porquê.'], 'Não escolhi ingredientes.',
    'Ingredientes da época?', ['Não.', 'Pensei.', 'Sim.', 'Sim, e expliquei.'], 'Não escolhi.'),
  'ATI-014|3|1': f('Hoje, fizeste a quantidade certa?', ['Muito a mais.', 'Um bocado a mais.', 'A certa.', 'A certa, e pesei antes.'], undefined,
    'Quantidade certa?', ['Muito a mais.', 'Um pouco a mais.', 'Sim.', 'Sim, e pesei.']),
  // ── ATI-019 Autoconfiança ──
  'ATI-019|1|0': f('Hoje, pediram-te uma coisa nova. O que fizeste?', ['Disse que não era capaz.', 'Fiz com medo.', 'Fiz com calma.', 'Fiz e gostei do resultado.'], 'Não me pediram.',
    'Coisa nova. E tu?', ['Não fui capaz.', 'Com medo.', 'Fiz.', 'Gostei.'], 'Não pediram.'),
  'ATI-019|1|1': f('Hoje, apresentaste o teu trabalho?', ['Não quis.', 'A medo.', 'Com segurança.', 'Com segurança e expliquei.'], undefined,
    'Mostraste o trabalho?', ['Não.', 'A medo.', 'Sim.', 'Sim, e expliquei.']),
  'ATI-019|2|0': f('Hoje, enganaste-te. O que pensaste?', ['Que não presto.', 'Fiquei em baixo.', 'Que acontece.', 'Que acontece, e aprendi.'], 'Não me enganei.',
    'Enganaste-te. Pensaste?', ['Não presto.', 'Fiquei triste.', 'Acontece.', 'Aprendi.'], 'Não me enganei.'),
  'ATI-019|2|1': f('Hoje, disseste a tua opinião?', ['Não.', 'Só a um amigo.', 'À equipa.', 'À equipa, e defendi-a.'], undefined,
    'Disseste o que pensas?', ['Não.', 'A um amigo.', 'À equipa.', 'E defendi.']),
  'ATI-019|3|0': f('Hoje, criticaram o teu trabalho. O que fizeste?', ['Desisti.', 'Fiquei chateado.', 'Pensei no que melhorar.', 'Agradeci e melhorei.'], 'Ninguém criticou.',
    'Criticaram. E tu?', ['Desisti.', 'Chateei-me.', 'Pensei.', 'Melhorei.'], 'Não criticaram.'),
  'ATI-019|3|1': f('Hoje, fizeste uma tarefa difícil?', ['Pedi a outro.', 'Com muita ajuda.', 'Sozinho/a.', 'Sozinho/a e quero repetir.'], undefined,
    'Tarefa difícil?', ['Pedi a outro.', 'Com ajuda.', 'Sozinho/a.', 'E quero mais.']),
  // ── ATI-020 Postura profissional ──
  'ATI-020|1|0': f('Hoje, entrou alguém de fora. Como estiveste?', ['A brincar.', 'Parei, sem cumprimentar.', 'Cumprimentei e trabalhei.', 'Cumprimentei e fui simpático.'], 'Não entrou ninguém.',
    'Alguém de fora. Cumprimentaste?', ['Não.', 'Parei só.', 'Sim.', 'Sim, simpático.'], 'Não entrou.'),
  'ATI-020|1|1': f('Hoje, disseste asneiras?', ['Sim, várias.', 'Uma.', 'Não.', 'Não, e usei os nomes certos.'], undefined,
    'Disseste asneiras?', ['Várias.', 'Uma.', 'Não.', 'Não, nenhuma.']),
  'ATI-020|2|0': f('Hoje, erraste à frente de alguém. Como reagiste?', ['Fiz uma cena.', 'Atrapalhei-me.', 'Assumi e corrigi.', 'Assumi, corrigi e continuei bem.'], 'Não errei à frente de ninguém.',
    'Erraste à frente. E tu?', ['Fiz cena.', 'Atrapalhei-me.', 'Corrigi.', 'Corrigi bem.'], 'Não errei.'),
  'ATI-020|2|1': f('Hoje, estiveste concentrado no teu posto?', ['Não, encostado ou a passear.', 'Às vezes distraído.', 'Sim.', 'Sim, e pronto a ajudar.'], undefined,
    'Concentrado?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, e ajudei.']),
  'ATI-020|3|0': f('Hoje, deram-te uma ordem («ouvido!»). Respondeste?', ['Não.', 'Tarde.', 'Logo.', 'Logo, e fiz a tempo.'], 'Não houve.',
    'Respondeste «ouvido»?', ['Não.', 'Tarde.', 'Sim.', 'Sim, e fiz.'], 'Não houve.'),
  'ATI-020|3|1': f('Hoje, chegaste a horas e bem apresentado?', ['Não.', 'Falhou uma coisa.', 'Sim.', 'Sim, antes da hora.'], undefined,
    'A horas e arranjado?', ['Não.', 'Quase.', 'Sim.', 'Sim, cedo.']),
  // ── ATI-021 Sentido crítico ──
  'ATI-021|1|0': f('Hoje, viste o prato antes de entregar?', ['Não.', 'Por alto.', 'Provei e comparei com a ficha.', 'Provei, comparei e corrigi.'], 'Não fiz pratos.',
    'Provaste antes de entregar?', ['Não.', 'Por alto.', 'Sim.', 'Sim, e corrigi.'], 'Não fiz.'),
  'ATI-021|1|1': f('Hoje, sabes o que correu bem e mal?', ['Não.', 'Só o que correu bem.', 'Sim, os dois.', 'Sim, e o que vou mudar.'], undefined,
    'O que correu bem e mal?', ['Não sei.', 'Só o bem.', 'Sei os dois.', 'E o que mudar.']),
  'ATI-021|2|0': f('Hoje, viste uma informação nova. O que fizeste?', ['Acreditei logo.', 'Desconfiei, mas não vi.', 'Confirmei no manual.', 'Confirmei e expliquei.'], 'Não vi informação nova.',
    'Informação nova. Confirmaste?', ['Não.', 'Desconfiei.', 'Sim.', 'Sim, e expliquei.'], 'Não vi.'),
  'ATI-021|2|1': f('Hoje, compararam o teu trabalho com outra equipa?', ['Não.', 'Só para criticar.', 'Sim, e aprendi.', 'Sim, e disse o que fizeram bem.'], undefined,
    'Viste outra equipa?', ['Não.', 'Para criticar.', 'Para aprender.', 'E elogiei.']),
  'ATI-021|3|0': f('Hoje, provaste o prato de um colega. O que disseste?', ['Que estava mau.', 'Que estava bom, sem pensar.', 'O bom e o que melhorar.', 'O bom, o que melhorar e como.'], 'Não provei.',
    'Prato de um colega. Disseste?', ['Está mau.', 'Está bom.', 'O bom e o mau.', 'E como melhorar.'], 'Não provei.'),
  'ATI-021|3|1': f('Hoje, perguntaste porque se faz assim?', ['Não.', 'Pensei, mas não perguntei.', 'Perguntei.', 'Perguntei e percebi.'], undefined,
    'Perguntaste porquê?', ['Não.', 'Pensei.', 'Perguntei.', 'E percebi.']),
};
