// ============================================================
// Perguntas novas dos 5 C (Rosa, out/2026): Colaborativo, Consciente e
// Criativo com perguntas suficientes para um ano inteiro sem o aluno
// sentir que responde sempre ao mesmo.
//
// Mesmo formato das de triagem5c.ts: situação de HOJE, 4 respostas do
// mais fraco para o mais forte (valem 2, 3, 4 e 5), a frase «não houve
// ocasião» (que não conta), e a versão fácil de ler (medidas seletivas
// e adicionais).
//
// AINDA NÃO ESTÃO LIGADAS À APLICAÇÃO: primeiro a Rosa lê e aprova.
// ============================================================
import type { PerguntaCO, LadoCO } from './triagem5c';

const q = (chave: 'co' | 'cr' | 'cl') => (id: string, lado: LadoCO, titulo: string, pergunta: string, frases: string[], semOcasiao: string,
  perguntaSimples: string, frasesSimples: string[], semOcasiaoSimples: string): PerguntaCO =>
  ({ id, lado, chave: chave as any, sigla: (chave === 'co' ? 'CO' : chave === 'cr' ? 'CR' : 'CL') as any, titulo, pergunta, frases, semOcasiao,
    perguntaSimples, frasesSimples, semOcasiaoSimples });
const cl = q('cl'), co = q('co'), cr = q('cr');

// ════════════════════════════════════════════════════════════
// COLABORATIVO — 15 novas (havia 2)
// ════════════════════════════════════════════════════════════
export const BANCO_CL_NOVO: PerguntaCO[] = [
  cl('cl03', 'outros', 'Dividir o trabalho',
    'Hoje, quando a equipa dividiu o trabalho, o que fizeste?',
    ['Fiquei com o que me deram, sem dizer nada.', 'Escolhi a parte de que gostava mais.', 'Ajudei a dividir de forma justa.', 'Ajudei a dividir e fiquei com uma parte difícil.'],
    'Hoje não houve trabalho de equipa (o professor confirma).',
    'Hoje, como dividiram o trabalho?',
    ['Fiquei com o que me deram.', 'Escolhi a parte mais fácil.', 'Ajudei a dividir bem.', 'Ajudei e fiquei com uma parte difícil.'], 'Hoje trabalhei sozinho/a.'),
  cl('cl04', 'outros', 'Colega atrasado',
    'Hoje, quando um colega ficou atrasado no trabalho, o que fizeste?',
    ['Continuei só no meu.', 'Disse-lhe para se despachar.', 'Ajudei-o quando acabei o meu.', 'Combinei com ele como acabarmos juntos a tempo.'],
    'Hoje ninguém ficou atrasado (o professor confirma).',
    'Hoje um colega atrasou-se. O que fizeste?',
    ['Nada.', 'Disse-lhe para se despachar.', 'Ajudei depois de acabar.', 'Ajudei e acabámos juntos.'], 'Ninguém se atrasou.'),
  cl('cl05', 'outros', 'Passar a informação',
    'Hoje, quando soubeste uma coisa importante (um tempo, uma mudança, um cuidado), o que fizeste?',
    ['Guardei para mim.', 'Disse só a um amigo.', 'Disse à equipa.', 'Disse à equipa e confirmei que todos perceberam.'],
    'Hoje não houve nada para passar (o professor confirma).',
    'Hoje soubeste uma coisa importante. O que fizeste?',
    ['Não disse.', 'Disse a um amigo.', 'Disse à equipa.', 'Disse e vi se perceberam.'], 'Não houve nada.'),
  cl('cl06', 'outros', 'Pedir ajuda',
    'Hoje, quando precisaste de ajuda de um colega, como pediste?',
    ['Não pedi e fiquei parado.', 'Pedi de forma brusca.', 'Pedi com educação.', 'Pedi com educação e depois ajudei-o também.'],
    'Hoje não precisei de ajuda (o professor confirma).',
    'Hoje pediste ajuda a um colega?',
    ['Não pedi e fiquei parado.', 'Pedi mal.', 'Pedi bem.', 'Pedi bem e ajudei-o depois.'], 'Não precisei.'),
  cl('cl07', 'outros', 'Ideias da equipa',
    'Hoje, quando a equipa estava a decidir, o que fizeste?',
    ['Não disse nada.', 'Disse a minha ideia e não ouvi as outras.', 'Disse a minha ideia e ouvi as outras.', 'Ajudei a juntar as ideias numa decisão de todos.'],
    'Hoje a equipa não decidiu nada (o professor confirma).',
    'Hoje a equipa decidiu uma coisa. O que fizeste?',
    ['Fiquei calado.', 'Só disse a minha ideia.', 'Disse e ouvi os outros.', 'Ajudei a decidir juntos.'], 'Não decidimos nada.'),
  cl('cl08', 'outros', 'Material partilhado',
    'Hoje, com o material que a equipa partilhava, o que fizeste?',
    ['Fiquei com o que precisava e não larguei.', 'Emprestei só quando me pediram.', 'Emprestei sem me pedirem.', 'Organizei o material para toda a equipa ter o que precisava.'],
    'Hoje não houve material partilhado (o professor confirma).',
    'Hoje partilhaste o material?',
    ['Não larguei.', 'Só quando pediram.', 'Sem pedirem.', 'Organizei para todos.'], 'Não havia material para partilhar.'),
  cl('cl09', 'outros', 'Arrumar juntos',
    'Hoje, na arrumação final, o que fizeste?',
    ['Saí e deixei para os outros.', 'Arrumei só a minha parte.', 'Arrumei a minha parte e ajudei um colega.', 'Ajudei até estar tudo arrumado.'],
    'Hoje não houve arrumação (o professor confirma).',
    'Hoje ajudaste a arrumar?',
    ['Não.', 'Só a minha parte.', 'A minha e ajudei um colega.', 'Ajudei até ao fim.'], 'Não houve arrumação.'),
  cl('cl10', 'outros', 'Erro de equipa',
    'Hoje, quando a equipa errou, o que fizeste?',
    ['Culpei alguém.', 'Disse que não tinha sido eu.', 'Ajudei a corrigir.', 'Ajudei a corrigir e combinámos como não repetir.'],
    'Hoje a equipa não errou (o professor confirma).',
    'Hoje a equipa errou. O que fizeste?',
    ['Culpei alguém.', 'Disse que não fui eu.', 'Ajudei a corrigir.', 'Corrigimos e combinámos.'], 'Não erramos.'),
  cl('cl11', 'outros', 'Colega novo ou sozinho',
    'Hoje, quando um colega estava sozinho ou era novo no grupo, o que fizeste?',
    ['Não liguei.', 'Falei com ele só quando precisei.', 'Chamei-o para trabalhar connosco.', 'Chamei-o e expliquei-lhe como trabalhamos.'],
    'Hoje ninguém estava sozinho (o professor confirma).',
    'Hoje um colega estava sozinho. O que fizeste?',
    ['Nada.', 'Só falei quando precisei.', 'Chamei-o.', 'Chamei-o e expliquei.'], 'Ninguém estava sozinho.'),
  cl('cl12', 'outros', 'Ensinar um colega',
    'Hoje, quando sabias fazer uma coisa que um colega não sabia, o que fizeste?',
    ['Fiz por ele.', 'Disse-lhe para ver no manual.', 'Expliquei-lhe como se faz.', 'Expliquei e vi-o fazer até lhe sair bem.'],
    'Hoje não houve ocasião (o professor confirma).',
    'Hoje ensinaste um colega?',
    ['Fiz por ele.', 'Mandei-o ver no manual.', 'Expliquei.', 'Expliquei e vi-o fazer.'], 'Não houve ocasião.'),
  cl('cl13', 'outros', 'Ritmo da equipa',
    'Hoje, com o ritmo da equipa, como foi?',
    ['Fui ao meu ritmo, sem ligar aos outros.', 'Atrasei ou apressei os outros.', 'Acertei o meu ritmo com a equipa.', 'Ajudei a equipa toda a manter o ritmo certo.'],
    'Hoje não trabalhei em equipa (o professor confirma).',
    'Hoje acompanhaste a tua equipa?',
    ['Fui ao meu ritmo.', 'Atrasei os outros.', 'Acompanhei.', 'Ajudei todos a acompanhar.'], 'Trabalhei sozinho/a.'),
  cl('cl14', 'outros', 'Elogiar',
    'Hoje, quando um colega fez um bom trabalho, o que fizeste?',
    ['Não disse nada.', 'Disse só a outros, não a ele.', 'Disse-lhe que estava bom.', 'Disse-lhe o que estava bom e porquê.'],
    'Hoje não houve ocasião (o professor confirma).',
    'Hoje elogiaste um colega?',
    ['Não.', 'Só disse a outros.', 'Disse-lhe.', 'Disse-lhe e expliquei porquê.'], 'Não houve ocasião.'),
  cl('cl15', 'outros', 'Funções na equipa',
    'Hoje, com a tua função na equipa (líder, registos, arrumação…), como foi?',
    ['Não fiz a minha função.', 'Fiz só uma parte.', 'Fiz a minha função.', 'Fiz a minha função e ajudei os outros nas deles.'],
    'Hoje não havia funções (o professor confirma).',
    'Hoje fizeste a tua função na equipa?',
    ['Não.', 'Só uma parte.', 'Sim.', 'Sim, e ajudei os outros.'], 'Não havia funções.'),
  cl('cl16', 'outros', 'Opinião diferente',
    'Hoje, quando um colega tinha uma opinião diferente, o que fizeste?',
    ['Fiz à minha maneira.', 'Discuti até ele desistir.', 'Ouvi e chegámos a acordo.', 'Ouvi, experimentámos as duas e escolhemos juntos.'],
    'Hoje não houve opiniões diferentes (o professor confirma).',
    'Hoje um colega pensava diferente. O que fizeste?',
    ['Fiz à minha maneira.', 'Discuti.', 'Chegámos a acordo.', 'Experimentámos e escolhemos juntos.'], 'Pensávamos igual.'),
  cl('cl17', 'outros', 'Outra equipa',
    'Hoje, quando outra equipa precisou de alguma coisa, o que fizeste?',
    ['Não liguei.', 'Ajudei só porque o professor pediu.', 'Ajudei sem me pedirem.', 'Ajudei e combinei com a minha equipa para não nos atrasarmos.'],
    'Hoje nenhuma equipa precisou (o professor confirma).',
    'Hoje ajudaste outra equipa?',
    ['Não.', 'Só porque me mandaram.', 'Sim, sem pedirem.', 'Sim, e combinei com a minha equipa.'], 'Ninguém precisou.'),
];

// ════════════════════════════════════════════════════════════
// CONSCIENTE — 13 novas (havia 22)
// ════════════════════════════════════════════════════════════
export const BANCO_CO_NOVO: PerguntaCO[] = [
  // ── Os outros ──
  co('co23', 'outros', 'Barulho e espaço',
    'Hoje, pensaste no barulho e no espaço que ocupavas, para não incomodar os outros?',
    ['Não pensei e incomodei.', 'Pensei só quando me chamaram a atenção.', 'Tive cuidado sozinho.', 'Tive cuidado e ajudei a turma a ter também.'],
    '', 'Hoje tiveste cuidado para não incomodar?',
    ['Não.', 'Só quando me avisaram.', 'Sim.', 'Sim, e ajudei os outros.'], ''),
  co('co24', 'outros', 'Quem limpa',
    'Hoje, pensaste em quem vai limpar a cozinha depois de nós?',
    ['Não pensei e deixei sujo.', 'Deixei uma parte suja.', 'Deixei limpo o que era meu.', 'Deixei limpo e ajudei a limpar o resto.'],
    '', 'Hoje deixaste a cozinha limpa?',
    ['Não.', 'Só uma parte.', 'O meu sim.', 'O meu e ajudei no resto.'], ''),
  co('co25', 'outros', 'Alergias',
    'Hoje, pensaste se alguém que vai comer pode ter alergias ou não poder comer alguma coisa?',
    ['Não pensei.', 'Pensei, mas não fiz nada.', 'Confirmei os ingredientes.', 'Confirmei e avisei a equipa.'],
    'Hoje não fizemos comida para ninguém (o professor confirma).',
    'Hoje pensaste nas alergias?',
    ['Não.', 'Pensei mas não fiz nada.', 'Confirmei.', 'Confirmei e avisei.'], 'Não fizemos comida.'),
  co('co26', 'outros', 'Colega com dificuldades',
    'Hoje, reparaste se algum colega tinha mais dificuldade do que tu?',
    ['Não reparei.', 'Reparei, mas não fiz nada.', 'Ofereci ajuda.', 'Ajudei sem o deixar envergonhado.'],
    'Hoje ninguém teve mais dificuldade (o professor confirma).',
    'Hoje viste um colega com dificuldade?',
    ['Não reparei.', 'Vi, mas não fiz nada.', 'Ofereci ajuda.', 'Ajudei com cuidado.'], 'Ninguém teve.'),
  // ── Eu próprio ──
  co('co27', 'si', 'O que me distrai',
    'Hoje, o que te distraiu, e o que fizeste?',
    ['Distraí-me muito e não fiz nada.', 'Distraí-me e só voltei quando me chamaram.', 'Reparei que estava distraído e voltei ao trabalho.', 'Afastei o que me distraía (telemóvel, conversa) antes de começar.'],
    '', 'Hoje distraíste-te?',
    ['Muito.', 'Sim, até me chamarem.', 'Um pouco, mas voltei.', 'Não, afastei o que distrai.'], ''),
  co('co28', 'si', 'Como me senti',
    'Hoje, como te sentiste na aula, e o que fizeste com isso?',
    ['Senti-me mal e descarreguei nos outros.', 'Senti-me mal e fechei-me.', 'Percebi como estava e continuei a trabalhar.', 'Percebi como estava e falei com alguém (professor ou colega).'],
    '', 'Hoje, como te sentiste?',
    ['Mal, e descarreguei.', 'Mal, e fechei-me.', 'Percebi e continuei.', 'Percebi e falei com alguém.'], ''),
  co('co29', 'si', 'Os meus objetivos',
    'Hoje, sabias o que querias melhorar nesta aula?',
    ['Não pensei nisso.', 'Pensei, mas esqueci-me.', 'Sim, e tentei.', 'Sim, tentei e consegui pelo menos uma parte.'],
    '', 'Hoje querias melhorar alguma coisa?',
    ['Não pensei.', 'Esqueci-me.', 'Sim, e tentei.', 'Sim, e consegui.'], ''),
  co('co30', 'si', 'O meu ritmo',
    'Hoje, o teu ritmo de trabalho estava certo para a aula?',
    ['Fui muito devagar e atrasei.', 'Fui depressa demais e enganei-me.', 'Fui ao ritmo certo.', 'Fui ao ritmo certo e acertei-o quando foi preciso.'],
    '', 'Hoje o teu ritmo estava bom?',
    ['Fui muito devagar.', 'Fui depressa demais.', 'Estava bom.', 'Estava bom e acertei quando foi preciso.'], ''),
  co('co31', 'si', 'Assumir',
    'Hoje, houve alguma coisa que fizeste mal e que assumiste?',
    ['Fiz mal e não assumi.', 'Assumi só quando me apanharam.', 'Assumi logo.', 'Assumi logo e corrigi.'],
    'Hoje não fiz nada mal (o professor confirma).',
    'Hoje assumiste um erro?',
    ['Não assumi.', 'Só quando me apanharam.', 'Assumi logo.', 'Assumi e corrigi.'], 'Não fiz nada mal.'),
  // ── O esforço do professor ──
  co('co32', 'professor', 'A preparação da aula',
    'Hoje, reparaste no que o professor teve de preparar para esta aula (ingredientes, fichas, material)?',
    ['Não pensei nisso.', 'Reparei, mas desperdicei.', 'Reparei e usei com cuidado.', 'Reparei, usei com cuidado e agradeci.'],
    '', 'Hoje pensaste no que o professor preparou?',
    ['Não.', 'Sim, mas desperdicei.', 'Sim, e tive cuidado.', 'Sim, e agradeci.'], ''),
  co('co33', 'professor', 'Ajuda individual',
    'Hoje, quando o professor te ajudou sozinho, o que fizeste?',
    ['Não liguei.', 'Ouvi, mas não mudei.', 'Ouvi e mudei.', 'Ouvi, mudei e mostrei-lhe o resultado.'],
    'Hoje o professor não me ajudou sozinho (o professor confirma).',
    'Hoje o professor ajudou-te. O que fizeste?',
    ['Não liguei.', 'Ouvi, mas não mudei.', 'Mudei.', 'Mudei e mostrei.'], 'Não me ajudou.'),
  co('co34', 'professor', 'Respeitar o tempo da turma',
    'Hoje, enquanto o professor ajudava outro colega, o que fizeste?',
    ['Interrompi para ser atendido.', 'Fiquei parado à espera.', 'Continuei o que podia fazer.', 'Continuei e ajudei um colega com a mesma dúvida.'],
    '', 'Hoje esperaste pelo professor?',
    ['Interrompi.', 'Fiquei parado.', 'Continuei a trabalhar.', 'Continuei e ajudei um colega.'], ''),
  co('co35', 'professor', 'Seguir o conselho',
    'Hoje, lembraste-te de um conselho que o professor te deu noutra aula?',
    ['Não me lembrei.', 'Lembrei-me, mas não usei.', 'Lembrei-me e usei.', 'Usei e disse-lhe que tinha resultado.'],
    'Hoje é a primeira aula com este professor (o professor confirma).',
    'Hoje usaste um conselho do professor?',
    ['Não me lembrei.', 'Lembrei, mas não usei.', 'Usei.', 'Usei e disse-lhe.'], 'É a primeira aula.'),
];

// ════════════════════════════════════════════════════════════
// CRIATIVO — 20 novas (havia 15)
// ════════════════════════════════════════════════════════════
export const BANCO_CR_NOVO: PerguntaCO[] = [
  // ── Resolver imprevistos ──
  cr('cr16', 'resolver', 'Ingrediente diferente',
    'Hoje, quando um ingrediente não era igual ao da ficha, o que fizeste?',
    ['Parei e esperei.', 'Usei na mesma, sem pensar.', 'Pensei em como acertar a receita.', 'Acertei a receita e expliquei porquê.'],
    'Hoje os ingredientes eram iguais (o professor confirma).',
    'Hoje um ingrediente era diferente. O que fizeste?',
    ['Parei.', 'Usei sem pensar.', 'Pensei em como acertar.', 'Acertei e expliquei.'], 'Eram iguais.'),
  cr('cr17', 'resolver', 'Sabor errado',
    'Hoje, quando o sabor não estava bem, o que fizeste?',
    ['Entreguei assim.', 'Pus mais sal sem provar outra vez.', 'Provei, acertei e voltei a provar.', 'Acertei e descobri porque tinha ficado assim.'],
    'Hoje o sabor estava bem à primeira (o professor confirma).',
    'Hoje o sabor não estava bem. O que fizeste?',
    ['Entreguei assim.', 'Pus sal sem provar.', 'Acertei e provei.', 'Acertei e percebi porquê.'], 'Estava bem.'),
  cr('cr18', 'resolver', 'Textura',
    'Hoje, quando a textura não ficou certa (grumos, demasiado líquido, duro), o que fizeste?',
    ['Deixei ficar.', 'Pedi ao professor para resolver.', 'Tentei uma maneira de corrigir.', 'Corrigi e anotei o que fazer da próxima vez.'],
    'Hoje a textura ficou certa (o professor confirma).',
    'Hoje a textura não ficou bem. O que fizeste?',
    ['Deixei.', 'Pedi ao professor.', 'Tentei corrigir.', 'Corrigi e anotei.'], 'Ficou bem.'),
  cr('cr19', 'resolver', 'Pouco espaço',
    'Hoje, quando havia pouco espaço ou poucos utensílios, o que fizeste?',
    ['Fiquei à espera.', 'Disputei com os colegas.', 'Organizei-me com o que havia.', 'Organizei-me e ajudei a equipa a partilhar melhor.'],
    'Hoje havia espaço e utensílios para todos (o professor confirma).',
    'Hoje havia pouco espaço. O que fizeste?',
    ['Esperei.', 'Disputei.', 'Organizei-me.', 'Organizei-me e ajudei.'], 'Havia espaço.'),
  cr('cr20', 'resolver', 'Quantidades',
    'Hoje, quando foi preciso fazer mais ou menos doses do que a ficha, o que fizeste?',
    ['Fiz as quantidades da ficha na mesma.', 'Fiz a olho.', 'Fiz as contas e acertei as quantidades.', 'Fiz as contas, acertei e confirmei com um colega.'],
    'Hoje não foi preciso mudar as doses (o professor confirma).',
    'Hoje mudaste as quantidades?',
    ['Não mudei.', 'Fiz a olho.', 'Fiz as contas.', 'Fiz as contas e confirmei.'], 'Não foi preciso.'),
  cr('cr21', 'resolver', 'Tempo apertado',
    'Hoje, quando o tempo estava a acabar, o que fizeste?',
    ['Entrei em pânico ou parei.', 'Fiz tudo à pressa e mal.', 'Escolhi o mais importante e acabei.', 'Reorganizei os passos e acabei a tempo e bem.'],
    'Hoje houve tempo de sobra (o professor confirma).',
    'Hoje o tempo estava a acabar. O que fizeste?',
    ['Parei.', 'Fiz tudo à pressa.', 'Fiz o mais importante.', 'Reorganizei e acabei bem.'], 'Houve tempo.'),
  cr('cr22', 'resolver', 'Sem resposta',
    'Hoje, quando ninguém te sabia responder a uma dúvida, o que fizeste?',
    ['Desisti.', 'Fiz ao calhas.', 'Procurei no manual ou na ficha.', 'Procurei, experimentei e confirmei depois.'],
    'Hoje não tive dúvidas assim (o professor confirma).',
    'Hoje ninguém sabia responder. O que fizeste?',
    ['Desisti.', 'Fiz ao calhas.', 'Procurei no manual.', 'Procurei e experimentei.'], 'Não tive dúvidas.'),
  // ── Ter ideias e experimentar ──
  cr('cr23', 'ideias', 'Nome do prato',
    'Hoje, se tivesses de dar um nome novo ao prato, conseguias?',
    ['Não pensei nisso.', 'Pensei, mas não me ocorreu nada.', 'Sim, tive uma ideia.', 'Sim, e expliquei porque ficava bem.'],
    'Hoje não fizemos pratos (o professor confirma).',
    'Hoje pensaste num nome para o prato?',
    ['Não.', 'Não me ocorreu.', 'Sim.', 'Sim, e expliquei.'], 'Não fizemos pratos.'),
  cr('cr24', 'ideias', 'Outro ingrediente',
    'Hoje, pensaste num ingrediente que podia ficar bem neste prato?',
    ['Não pensei.', 'Pensei, mas não disse.', 'Disse a ideia ao professor.', 'Disse e experimentámos, com autorização.'],
    'Hoje não fizemos pratos (o professor confirma).',
    'Hoje pensaste noutro ingrediente?',
    ['Não.', 'Pensei mas não disse.', 'Disse ao professor.', 'Disse e experimentámos.'], 'Não fizemos pratos.'),
  cr('cr25', 'ideias', 'Cores e formas',
    'Hoje, pensaste nas cores e nas formas do prato antes de empratar?',
    ['Pus de qualquer maneira.', 'Pensei um bocadinho.', 'Pensei e empratei com cuidado.', 'Experimentei duas maneiras e escolhi a melhor.'],
    'Hoje não empratámos (o professor confirma).',
    'Hoje pensaste em como empratar?',
    ['Não.', 'Um bocadinho.', 'Sim, com cuidado.', 'Experimentei duas maneiras.'], 'Não empratámos.'),
  cr('cr26', 'ideias', 'Juntar o que sei',
    'Hoje, usaste uma técnica de outra aula numa coisa nova?',
    ['Não.', 'Pensei, mas não usei.', 'Usei uma técnica de outra aula.', 'Usei e expliquei a ligação a um colega.'],
    'Hoje era tudo novo para mim (o professor confirma).',
    'Hoje usaste uma coisa que aprendeste antes?',
    ['Não.', 'Pensei mas não usei.', 'Usei.', 'Usei e expliquei.'], 'Era tudo novo.'),
  cr('cr27', 'ideias', 'Pergunta curiosa',
    'Hoje, fizeste alguma pergunta por curiosidade (porque é que isto acontece?)',
    ['Não.', 'Pensei, mas não perguntei.', 'Perguntei.', 'Perguntei e fui saber mais.'],
    '', 'Hoje fizeste uma pergunta por curiosidade?',
    ['Não.', 'Pensei mas não perguntei.', 'Perguntei.', 'Perguntei e fui saber mais.'], ''),
  cr('cr28', 'ideias', 'Prato para outra pessoa',
    'Hoje, se este prato fosse para uma criança ou para um idoso, o que mudavas?',
    ['Não sei.', 'Pensei, mas não sei dizer.', 'Sei dizer uma coisa que mudava.', 'Sei dizer o que mudava e porquê.'],
    'Hoje não fizemos pratos (o professor confirma).',
    'Hoje, o que mudavas no prato para uma criança?',
    ['Não sei.', 'Não sei dizer.', 'Sei uma coisa.', 'Sei o que mudava e porquê.'], 'Não fizemos pratos.'),
  // ── Melhorar o que já existe ──
  cr('cr29', 'melhorar', 'Menos passos',
    'Hoje, encontraste uma maneira de fazer uma tarefa com menos passos ou menos tempo?',
    ['Não pensei nisso.', 'Pensei, mas fiz igual.', 'Encontrei e usei.', 'Encontrei, usei e mostrei à equipa.'],
    '', 'Hoje fizeste uma coisa mais depressa?',
    ['Não pensei.', 'Pensei mas fiz igual.', 'Sim.', 'Sim, e mostrei à equipa.'], ''),
  cr('cr30', 'melhorar', 'A ficha técnica',
    'Hoje, viste alguma coisa na ficha técnica que podia estar mais clara?',
    ['Não li com atenção.', 'Li, mas não pensei nisso.', 'Vi uma coisa e disse ao professor.', 'Vi, disse e sugeri como escrever melhor.'],
    'Hoje não usámos ficha técnica (o professor confirma).',
    'Hoje a ficha podia estar mais clara?',
    ['Não li bem.', 'Não pensei.', 'Sim, e disse.', 'Sim, e sugeri como.'], 'Não usámos ficha.'),
  cr('cr31', 'melhorar', 'Menos lixo',
    'Hoje, encontraste uma maneira de fazer menos lixo ou gastar menos?',
    ['Não pensei nisso.', 'Pensei, mas não mudei.', 'Mudei uma coisa.', 'Mudei e ensinei aos colegas.'],
    '', 'Hoje gastaste menos?',
    ['Não pensei.', 'Pensei mas não mudei.', 'Mudei uma coisa.', 'Mudei e ensinei.'], ''),
  cr('cr32', 'melhorar', 'A bancada',
    'Hoje, mudaste a forma de organizar a bancada para trabalhar melhor?',
    ['Não.', 'Pensei, mas ficou igual.', 'Mudei uma coisa.', 'Mudei e resultou melhor do que antes.'],
    'Hoje não trabalhei na bancada (o professor confirma).',
    'Hoje organizaste melhor a bancada?',
    ['Não.', 'Ficou igual.', 'Mudei uma coisa.', 'Mudei e ficou melhor.'], 'Não usei a bancada.'),
  cr('cr33', 'melhorar', 'O que repetia',
    'Hoje, o que fizeste que queres repetir porque resultou?',
    ['Não sei.', 'Sei, mas não sei explicar.', 'Sei dizer o que resultou.', 'Sei dizer o que resultou e porquê.'],
    '', 'Hoje o que correu bem?',
    ['Não sei.', 'Não sei explicar.', 'Sei dizer.', 'Sei dizer e porquê.'], ''),
  cr('cr34', 'melhorar', 'Ajuda do colega',
    'Hoje, uma ideia de um colega ajudou-te a melhorar?',
    ['Não ouvi as ideias dos outros.', 'Ouvi, mas não usei.', 'Usei uma ideia de um colega.', 'Usei, melhorei-a e disse-lhe.'],
    'Hoje não houve ideias de colegas (o professor confirma).',
    'Hoje usaste uma ideia de um colega?',
    ['Não ouvi.', 'Ouvi mas não usei.', 'Usei.', 'Usei, melhorei e disse-lhe.'], 'Não houve ideias.'),
  cr('cr35', 'melhorar', 'Pedir opinião',
    'Hoje, pediste a alguém para provar ou ver o teu trabalho antes de acabar?',
    ['Não.', 'Pedi, mas não mudei nada.', 'Pedi e mudei uma coisa.', 'Pedi, mudei e voltei a pedir opinião.'],
    '', 'Hoje pediste opinião sobre o teu trabalho?',
    ['Não.', 'Pedi mas não mudei.', 'Pedi e mudei.', 'Pedi, mudei e voltei a pedir.'], ''),
];
