// ============================================================
// 5 C para os alunos com medidas ADICIONAIS (nível 3): ainda mais curtas
// do que a versão «simples» (que fica para as medidas seletivas).
// Uma ideia por frase, palavras do dia a dia. As 4 respostas valem o
// mesmo que nas outras versões (do mais fraco para o mais forte).
// Chave: o id da pergunta ('cl', 'cr', 'co' para as de base; cl02…,
// co01…, cr01… para os bancos).
// ============================================================

export interface VersaoMuitoSimples { pergunta: string; frases: [string, string, string, string]; semOcasiao?: string }
type R4 = [string, string, string, string];
const m = (pergunta: string, frases: R4, semOcasiao?: string): VersaoMuitoSimples => ({ pergunta, frases, ...(semOcasiao ? { semOcasiao } : {}) });

export const MUITO_SIMPLES_5C: Record<string, VersaoMuitoSimples> = {
  // ── De base ──
  cl: m('Ajudaste os colegas?', ['Não.', 'Quando pediram.', 'Sim, sem pedirem.', 'Ajudei todos.'], 'Trabalhei sozinho/a.'),
  cr: m('Foi difícil. E tu?', ['Pedi ajuda logo.', 'Tentei uma vez.', 'Tentei duas vezes.', 'Resolvi sozinho/a.']),
  co: m('Fizeste melhor do que antes?', ['Não.', 'Lembrei-me.', 'Sim, uma coisa.', 'Sim, e disse.'], 'É a primeira aula.'),
  // ── Colaborativo ──
  cl02: m('Arrumaste com os colegas?', ['Não.', 'Só o meu.', 'Sim.', 'Sim, tudo pronto.']),
  cl03: m('Dividiram o trabalho?', ['Calei-me.', 'Escolhi o fácil.', 'Dividi bem.', 'Fiquei com o difícil.'], 'Trabalhei sozinho/a.'),
  cl04: m('Colega atrasado. E tu?', ['Nada.', 'Apressei-o.', 'Ajudei.', 'Acabámos juntos.'], 'Ninguém se atrasou.'),
  cl05: m('Passaste a informação?', ['Não.', 'A um amigo.', 'À equipa.', 'E confirmei.'], 'Não houve.'),
  cl06: m('Pediste ajuda bem?', ['Não pedi.', 'Pedi mal.', 'Pedi bem.', 'E ajudei depois.'], 'Não precisei.'),
  cl07: m('Decidiram juntos?', ['Calei-me.', 'Só a minha ideia.', 'Ouvi todos.', 'Decidimos juntos.'], 'Não houve.'),
  cl08: m('Partilhaste o material?', ['Não.', 'Quando pediram.', 'Sim.', 'Para todos.'], 'Não havia.'),
  cl09: m('Ajudaste a arrumar?', ['Não.', 'Só o meu.', 'E de um colega.', 'Até ao fim.'], 'Não houve.'),
  cl10: m('A equipa errou. E tu?', ['Culpei.', 'Não fui eu.', 'Corrigi.', 'Combinámos.'], 'Não errámos.'),
  cl11: m('Colega sozinho. E tu?', ['Nada.', 'Pouco.', 'Chamei-o.', 'Chamei e expliquei.'], 'Ninguém sozinho.'),
  cl12: m('Ensinaste um colega?', ['Fiz por ele.', 'Mandei ler.', 'Expliquei.', 'Vi-o fazer.'], 'Não houve.'),
  cl13: m('Acompanhaste a equipa?', ['Não.', 'Atrasei.', 'Sim.', 'Ajudei todos.'], 'Trabalhei sozinho/a.'),
  cl14: m('Elogiaste um colega?', ['Não.', 'A outros.', 'Sim.', 'Sim, e porquê.'], 'Não houve.'),
  cl15: m('Fizeste a tua função?', ['Não.', 'Uma parte.', 'Sim.', 'E ajudei.'], 'Não havia.'),
  cl16: m('Pensavam diferente. E tu?', ['À minha maneira.', 'Discuti.', 'Acordo.', 'Escolhemos juntos.'], 'Pensávamos igual.'),
  cl17: m('Ajudaste outra equipa?', ['Não.', 'Mandaram.', 'Sim.', 'Sim, e combinei.'], 'Ninguém precisou.'),
  // ── Consciente ──
  co01: m('Colega precisou de ti?', ['Nada.', 'Só vi.', 'Perguntei.', 'Ajudei.'], 'Ninguém precisou.'),
  co02: m('Colega zangado. E tu?', ['Piorei.', 'Só vi.', 'Fiquei calmo/a.', 'Acalmei-o.'], 'Ninguém zangado.'),
  co03: m('Colega sozinho. E tu?', ['Nada.', 'Só vi.', 'Falei.', 'Chamei-o.'], 'Ninguém sozinho.'),
  co04: m('Fizeram troça de um colega?', ['Ri-me.', 'Só vi.', 'Não me ri.', 'Disse que não.'], 'Ninguém fez troça.'),
  co05: m('Colega enganou-se?', ['Fiz troça.', 'Só vi.', 'Não fiz troça.', 'Ajudei.'], 'Ninguém se enganou.'),
  co06: m('Colega novo. E tu?', ['Nada.', 'Só vi.', 'Mostrei.', 'Ajudei.'], 'Não houve.'),
  co07: m('Colega fez diferente?', ['Critiquei.', 'Nada.', 'Respeitei.', 'Ajudei.'], 'Não houve.'),
  co08: m('Cozinha arrumada?', ['Não.', 'Mais ou menos.', 'O meu sim.', 'Tudo.']),
  co09: m('Viste um perigo?', ['Nada.', 'Afastei-me.', 'Avisei.', 'Resolvi.'], 'Não vi.'),
  co10: m('Agradeceste?', ['Não.', 'Pensei.', 'Sim.', 'E ajudei.']),
  co11: m('Pensaste em quem come?', ['Não.', 'Pensei.', 'Higiene.', 'Alergias.'], 'Ninguém comia.'),
  co12: m('Comida no lixo?', ['Deitei.', 'Só vi.', 'Não deitei.', 'Aproveitei.'], 'Não houve.'),
  co13: m('Coisa difícil?', ['Não vi.', 'Escondi.', 'Disse.', 'Treinei.'], 'Não houve.'),
  co14: m('Fizeste o que sabes bem?', ['Não.', 'Calei-me.', 'Ofereci-me.', 'Ensinei.'], 'Não houve.'),
  co15: m('Cansado ou nervoso?', ['Fui mal-educado.', 'Trabalhei pior.', 'Respirei.', 'Pedi ajuda.'], 'Senti-me bem.'),
  co16: m('Tiveste dúvidas?', ['Correu mal.', 'Não perguntei.', 'Perguntei.', 'Perguntei sempre.'], 'Não tive.'),
  co17: m('Falaram do teu trabalho?', ['Chateei-me.', 'Não mudei.', 'Agradeci.', 'Melhorei.'], 'Não falaram.'),
  co18: m('Explicou outra vez?', ['Não ouvi.', 'Não fiz.', 'Fiz.', 'Mostrei.'], 'Não explicou.'),
  co19: m('Corrigiu-te?', ['Chateei-me.', 'Não mudei.', 'Corrigi.', 'Percebi.'], 'Não corrigiu.'),
  co20: m('Vieste preparado?', ['Não.', 'Desenrasquei.', 'Mais ou menos.', 'Sim.']),
  co21: m('Mais uma oportunidade?', ['Não aproveitei.', 'Só um pouco.', 'Aproveitei.', 'Aproveitei e agradeci.'], 'Não houve.'),
  co22: m('Deixaste ajudar todos?', ['Interrompi.', 'Às vezes.', 'Quase sempre.', 'Sim.']),
  co23: m('Incomodaste os outros?', ['Sim.', 'Avisaram-me.', 'Não.', 'Ajudei.']),
  co24: m('Deixaste limpo?', ['Não.', 'Uma parte.', 'O meu.', 'Tudo.']),
  co25: m('Viste as alergias?', ['Não.', 'Pensei.', 'Sim.', 'E avisei.'], 'Não houve comida.'),
  co26: m('Colega com dificuldade?', ['Não vi.', 'Nada.', 'Ofereci.', 'Ajudei.'], 'Não houve.'),
  co27: m('Distraíste-te?', ['Muito.', 'Sim.', 'Pouco.', 'Não.']),
  co28: m('Como te sentiste?', ['Descarreguei.', 'Fechei-me.', 'Continuei.', 'Falei.']),
  co29: m('Querias melhorar?', ['Não.', 'Esqueci-me.', 'Tentei.', 'Consegui.']),
  co30: m('Ritmo bom?', ['Devagar.', 'Depressa.', 'Bom.', 'Acertei.']),
  co31: m('Assumiste o erro?', ['Não.', 'Apanharam-me.', 'Sim.', 'E corrigi.'], 'Não errei.'),
  co32: m('O professor preparou tudo. E tu?', ['Não pensei.', 'Desperdicei.', 'Tive cuidado.', 'Agradeci.']),
  co33: m('O professor ajudou-te?', ['Não liguei.', 'Não mudei.', 'Mudei.', 'Mostrei.'], 'Não ajudou.'),
  co34: m('Esperaste pelo professor?', ['Interrompi.', 'Parei.', 'Trabalhei.', 'Ajudei.']),
  co35: m('Usaste um conselho?', ['Não.', 'Lembrei.', 'Usei.', 'Disse-lhe.'], 'É a primeira aula.'),
  // ── Criativo ──
  cr01: m('Faltou uma coisa. E tu?', ['Esperei.', 'Pedi.', 'Pensei.', 'Arranjei.'], 'Não faltou.'),
  cr02: m('Correu mal. E tu?', ['Desisti.', 'Pedi ajuda.', 'Tentei.', 'Refiz.'], 'Não correu mal.'),
  cr03: m('Pouco tempo. E tu?', ['Não acabei.', 'À pressa.', 'Mudei a ordem.', 'Acabámos.'], 'Houve tempo.'),
  cr04: m('Dúvida. E tu?', ['Parei.', 'Perguntei.', 'Vi a ficha.', 'Experimentei.'], 'Não tive.'),
  cr05: m('Máquina avariada?', ['Esperei.', 'Avisei.', 'Outra maneira.', 'Ficou bem.'], 'Não houve.'),
  cr06: m('Outra forma de empratar?', ['Não.', 'Pensei.', 'Disse.', 'Fiz.'], 'Não houve prato.'),
  cr07: m('Provaste?', ['Não.', 'Não mudei.', 'Corrigi.', 'Expliquei.'], 'Nada para provar.'),
  cr08: m('Outra maneira de fazer?', ['Não.', 'Pensei.', 'Perguntei.', 'Experimentámos.']),
  cr09: m('Usaste o que sabias?', ['Não.', 'Lembrei.', 'Usei.', 'Expliquei.']),
  cr10: m('Quiseste saber mais?', ['Não.', 'Pensei.', 'Perguntei.', 'Procurei.']),
  cr11: m('Maneira mais fácil?', ['Não.', 'Pensei.', 'Mudei.', 'Disse ao grupo.']),
  cr12: m('Sobrou comida?', ['Deitei fora.', 'Guardei.', 'Disse como.', 'Aproveitei.'], 'Não sobrou.'),
  cr13: m('Mudavas alguma coisa?', ['Não sei.', 'Não sei o quê.', 'Sei.', 'Disse.']),
  cr14: m('Erro antigo?', ['Repeti.', 'Tarde.', 'Não errei.', 'Ajudei.'], 'Não tinha.'),
  cr15: m('Boa ideia?', ['Não.', 'Não disse.', 'A um colega.', 'Foi usada.']),
  cr16: m('Ingrediente diferente?', ['Parei.', 'Sem pensar.', 'Pensei.', 'Acertei.'], 'Era igual.'),
  cr17: m('Sabor mal?', ['Entreguei.', 'Sal sem provar.', 'Acertei.', 'Percebi porquê.'], 'Estava bem.'),
  cr18: m('Textura mal?', ['Deixei.', 'Pedi.', 'Tentei.', 'Corrigi.'], 'Ficou bem.'),
  cr19: m('Pouco espaço?', ['Esperei.', 'Disputei.', 'Organizei.', 'Ajudei.'], 'Havia espaço.'),
  cr20: m('Mudaste as quantidades?', ['Não.', 'A olho.', 'Contas.', 'Confirmei.'], 'Não foi preciso.'),
  cr21: m('O tempo acabava?', ['Parei.', 'À pressa.', 'O importante.', 'Acabei bem.'], 'Houve tempo.'),
  cr22: m('Ninguém sabia. E tu?', ['Desisti.', 'Fiz à sorte.', 'Vi no manual.', 'Experimentei.'], 'Não houve.'),
  cr23: m('Nome para o prato?', ['Não.', 'Não ocorreu.', 'Sim.', 'E expliquei.'], 'Não houve prato.'),
  cr24: m('Outro ingrediente?', ['Não.', 'Não disse.', 'Disse.', 'Experimentámos.'], 'Não houve prato.'),
  cr25: m('Pensaste no empratamento?', ['Não.', 'Pouco.', 'Sim.', 'Duas maneiras.'], 'Não empratámos.'),
  cr26: m('Usaste o que aprendeste?', ['Não.', 'Pensei.', 'Usei.', 'Expliquei.'], 'Era tudo novo.'),
  cr27: m('Pergunta curiosa?', ['Não.', 'Pensei.', 'Perguntei.', 'Fui saber.']),
  cr28: m('Prato para uma criança?', ['Não sei.', 'Não sei dizer.', 'Uma coisa.', 'E porquê.'], 'Não houve prato.'),
  cr29: m('Mais depressa?', ['Não.', 'Igual.', 'Sim.', 'Mostrei.']),
  cr30: m('Ficha pouco clara?', ['Não li.', 'Não pensei.', 'Disse.', 'Sugeri.'], 'Sem ficha.'),
  cr31: m('Gastaste menos?', ['Não.', 'Pensei.', 'Mudei.', 'Ensinei.']),
  cr32: m('Bancada melhor?', ['Não.', 'Igual.', 'Mudei.', 'Ficou melhor.'], 'Sem bancada.'),
  cr33: m('O que correu bem?', ['Não sei.', 'Não sei dizer.', 'Sei.', 'E porquê.']),
  cr34: m('Ideia de um colega?', ['Não ouvi.', 'Não usei.', 'Usei.', 'Melhorei.'], 'Não houve.'),
  cr35: m('Pediste opinião?', ['Não.', 'Não mudei.', 'Mudei.', 'Pedi outra vez.']),
};
