// ============================================================
// Perguntas das atitudes mais fáceis de ler (Rosa, out/2026).
//
// Três níveis de alunos:
//   1 — sem medidas: as perguntas normais;
//   2 — medidas seletivas: «simples» (frases curtas, palavras do dia a dia);
//   3 — medidas adicionais: «muitoSimples» (ainda mais curtas, uma ideia
//       por frase, sem palavras difíceis).
// As 4 respostas valem o mesmo nos três níveis (do pior para o melhor).
//
// Chave: «ATI-001|par|pergunta». O par 0 é o de sempre
// (perguntas_atitudes.ts); os pares 1 a 3 são os novos
// (perguntasNovasAtitudes.ts). Nos eventos: «EV|ATI-001|pergunta».
// ============================================================

export interface VersaoFacil { pergunta: string; respostas: [string, string, string, string]; naoAconteceu?: string }
export interface VersoesFaceis { simples: VersaoFacil; muitoSimples: VersaoFacil }

type R4 = [string, string, string, string];
const f = (ps: string, rs: R4, ns: string | undefined, pm: string, rm: R4, nm?: string): VersoesFaceis => ({
  simples: { pergunta: ps, respostas: rs, ...(ns ? { naoAconteceu: ns } : {}) },
  muitoSimples: { pergunta: pm, respostas: rm, ...(nm ? { naoAconteceu: nm } : {}) },
});

/** As perguntas de sempre (par 0) e as dos eventos. */
export const FACEIS_DE_SEMPRE: Record<string, VersoesFaceis> = {
  // ── 1.º ano ──
  'ATI-001|0|0': f('Hoje, uma coisa correu mal no teu trabalho. O que fizeste?',
    ['Disse que não era culpa minha.', 'Só disse quando o professor perguntou.', 'Disse logo e corrigi.', 'Disse, corrigi e expliquei aos colegas.'], 'Hoje não correu nada mal.',
    'Correu mal. O que fizeste?', ['Escondi.', 'Disse quando perguntaram.', 'Disse e corrigi.', 'Corrigi e expliquei.'], 'Não correu mal.'),
  'ATI-001|0|1': f('Hoje, fizeste a tua tarefa até ao fim?',
    ['Não acabei.', 'Acabei porque me lembraram.', 'Acabei sozinho/a, a tempo.', 'Acabei, confirmei e avisei.'], undefined,
    'Acabaste a tarefa?', ['Não.', 'Com ajuda.', 'Sim, sozinho/a.', 'Sim, e avisei.']),
  'ATI-003|0|0': f('Hoje, como vieste vestido para a cozinha?',
    ['Faltava farda ou tinha anéis, unhas pintadas, cabelo solto.', 'Farda suja, ou sem touca ou avental.', 'Farda completa e limpa, cabelo preso.', 'Tudo bem, e ajudei um colega.'], 'Hoje não era preciso farda.',
    'Vieste com a farda?', ['Não.', 'Faltava uma coisa.', 'Sim, toda.', 'Sim, e ajudei um colega.'], 'Não era preciso.'),
  'ATI-003|0|1': f('Hoje, estavas limpo e arranjado?',
    ['Não, vim sujo ou despenteado.', 'Quase, faltou um pormenor.', 'Sim, limpo e com o cabelo preso.', 'Sim, e lembrei um colega.'], undefined,
    'Estavas limpo?', ['Não.', 'Quase.', 'Sim.', 'Sim, e ajudei.']),
  'ATI-005|0|0': f('Hoje, alguém te irritou ou houve pressa. O que fizeste?',
    ['Gritei ou respondi mal.', 'Fiquei nervoso e parei.', 'Respirei e continuei calmo.', 'Fiquei calmo e acalmei os outros.'], 'Hoje ninguém me irritou.',
    'Ficaste irritado?', ['Gritei.', 'Parei.', 'Respirei.', 'Acalmei os outros.'], 'Não fiquei.'),
  'ATI-005|0|1': f('Hoje, como falaste com os colegas?',
    ['Gritei ou falei mal.', 'Às vezes falei alto.', 'Falei sempre com calma.', 'Falei com calma e pedi silêncio.'], undefined,
    'Como falaste?', ['Gritei.', 'Alto.', 'Com calma.', 'Com calma e ajudei.']),
  'ATI-011|0|0': f('Hoje, como estava a tua bancada?',
    ['Desarrumada, perdi tempo.', 'Arrumada no início, depois não.', 'Arrumada e limpa o tempo todo.', 'Arrumada e ajudei outra bancada.'], 'Hoje não usei a bancada.',
    'A bancada estava arrumada?', ['Não.', 'Só no início.', 'Sim.', 'Sim, e ajudei.'], 'Não usei.'),
  'ATI-011|0|1': f('Hoje, trouxeste o teu material arrumado?',
    ['Esqueci-me de coisas.', 'Trouxe tudo, mas misturado.', 'Trouxe tudo arrumado.', 'Trouxe tudo e ajudei um colega.'], undefined,
    'Trouxeste o material?', ['Não.', 'Sim, misturado.', 'Sim, arrumado.', 'Sim, e ajudei.']),
  'ATI-013|0|0': f('Hoje, não percebeste uma coisa. O que fizeste?',
    ['Fiquei calado.', 'Perguntei a um colega.', 'Perguntei ao professor.', 'Perguntei e experimentei até conseguir.'], 'Hoje percebi tudo.',
    'Não percebeste. O que fizeste?', ['Nada.', 'Perguntei a um colega.', 'Perguntei ao professor.', 'Perguntei e consegui.'], 'Percebi tudo.'),
  'ATI-013|0|1': f('Hoje, o professor explicou ou corrigiu. O que fizeste?',
    ['Não ouvi ou fiquei chateado.', 'Ouvi, mas fiz à minha maneira.', 'Ouvi e fiz como ele disse.', 'Fiz como ele disse e perguntei mais.'], undefined,
    'O professor explicou. E tu?', ['Não ouvi.', 'Fiz à minha maneira.', 'Fiz como ele disse.', 'Fiz e perguntei.']),
  'ATI-015|0|0': f('Hoje, cumpriste as regras (horário, lavar as mãos)?',
    ['Falhei várias regras.', 'Falhei uma regra.', 'Cumpri todas.', 'Cumpri e lembrei um colega.'], undefined,
    'Cumpriste as regras?', ['Não.', 'Quase.', 'Sim.', 'Sim, e ajudei.']),
  'ATI-015|0|1': f('Hoje, o telemóvel ficou guardado?',
    ['Não, usei-o.', 'Fui vê-lo uma vez.', 'Sim, a aula toda.', 'Sim, e lembrei um colega.'], undefined,
    'Guardaste o telemóvel?', ['Não.', 'Quase.', 'Sim.', 'Sim, e ajudei.']),
  'ATI-016|0|0': f('Hoje, separaste a comida crua da cozinhada?',
    ['Não, misturei.', 'Às vezes.', 'Sempre, e lavei a tábua e a faca.', 'Sempre, e avisei um colega.'], 'Hoje não mexi em comida.',
    'Separaste cru e cozinhado?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, e avisei.'], 'Não mexi.'),
  'ATI-016|0|1': f('Hoje, lavaste as mãos?',
    ['Não.', 'Só quando mandaram.', 'Sim, sempre que era preciso.', 'Sim, e lembrei um colega.'], undefined,
    'Lavaste as mãos?', ['Não.', 'Quando mandaram.', 'Sim.', 'Sim, e ajudei.']),
  'ATI-017|0|0': f('Hoje, tiveste cuidado com facas e coisas quentes?',
    ['Não, andei com a faca na mão.', 'Quase sempre.', 'Sempre.', 'Sempre, e protegi um colega.'], 'Hoje não usei facas nem lume.',
    'Cuidado com facas e quente?', ['Não.', 'Quase.', 'Sim.', 'Sim, e avisei.'], 'Não usei.'),
  'ATI-017|0|1': f('Hoje, deixaste o chão e as passagens livres?',
    ['Não, corri ou deixei coisas no chão.', 'Às vezes.', 'Sim.', 'Sim, e avisei de um perigo.'], undefined,
    'O chão ficou livre?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, e avisei.']),
  // ── 2.º ano ──
  'ATI-002|0|0': f('Hoje, não sabias o passo seguinte. O que fizeste?',
    ['Fiquei parado.', 'Perguntei logo.', 'Vi a ficha e resolvi.', 'Resolvi e adiantei mais.'], 'Hoje soube sempre o que fazer.',
    'Não sabias o que fazer. E tu?', ['Parei.', 'Perguntei.', 'Vi a ficha.', 'Vi a ficha e adiantei.'], 'Soube sempre.'),
  'ATI-002|0|1': f('Hoje, começaste o trabalho sozinho/a?',
    ['Não, esperei.', 'Comecei, mas precisei de ajuda.', 'Sim, com a ficha.', 'Sim, e organizei tudo.'], undefined,
    'Começaste sozinho/a?', ['Não.', 'Com ajuda.', 'Sim.', 'Sim, e organizei.']),
  'ATI-007|0|0': f('Hoje, um colega estava triste ou com dificuldade. O que fizeste?',
    ['Gozei.', 'Não fiz nada.', 'Perguntei se estava bem.', 'Ajudei até ele ficar bem.'], 'Hoje não vi ninguém assim.',
    'Um colega estava mal. E tu?', ['Gozei.', 'Nada.', 'Perguntei.', 'Ajudei.'], 'Não vi.'),
  'ATI-007|0|1': f('Hoje, como falaste com os colegas?',
    ['Disse coisas que magoam.', 'Às vezes sem pensar.', 'Com respeito.', 'Com respeito e animei um colega.'], undefined,
    'Falaste bem com os colegas?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, e animei.']),
  'ATI-008|0|0': f('Hoje, numa conversa em grupo, o que fizeste?',
    ['Falei por cima.', 'Fiquei distraído.', 'Esperei a minha vez e ouvi.', 'Ouvi e usei a ideia de um colega.'], 'Hoje não houve conversa em grupo.',
    'Na conversa, ouviste?', ['Interrompi.', 'Distraí-me.', 'Ouvi.', 'Ouvi e usei a ideia.'], 'Não houve.'),
  'ATI-008|0|1': f('Hoje, alguém te explicou uma coisa. O que fizeste?',
    ['Interrompi.', 'Ouvi, mas perguntei outra vez.', 'Ouvi até ao fim e fiz.', 'Ouvi e repeti para confirmar.'], undefined,
    'Explicaram-te. Ouviste?', ['Não.', 'Mais ou menos.', 'Sim.', 'Sim, e repeti.']),
  'ATI-009|0|0': f('Hoje, como trabalhaste com a equipa?',
    ['Deixei o trabalho aos outros.', 'Só fiz a minha parte.', 'Fiz a minha parte e ajudei.', 'Ajudei sem pedirem.'], 'Hoje não havia equipa.',
    'Ajudaste a equipa?', ['Não.', 'Só a minha parte.', 'Ajudei.', 'Ajudei sem pedirem.'], 'Não havia equipa.'),
  'ATI-009|0|1': f('Hoje, no fim, ajudaste a arrumar?',
    ['Não.', 'Só o meu.', 'Sim, o de todos.', 'Sim, até ao fim.'], undefined,
    'Ajudaste a arrumar?', ['Não.', 'Só o meu.', 'Sim.', 'Sim, até ao fim.']),
  'ATI-010|0|0': f('Hoje, uma tarefa foi difícil. O que fizeste?',
    ['Desisti.', 'Tentei uma vez.', 'Tentei até conseguir.', 'Consegui e perguntei como melhorar.'], 'Hoje nada foi difícil.',
    'Foi difícil. Desististe?', ['Sim.', 'Tentei uma vez.', 'Não, consegui.', 'Consegui e melhorei.'], 'Não foi difícil.'),
  'ATI-010|0|1': f('Hoje, trabalhaste até ao fim?',
    ['Não, parei antes.', 'Só uma parte.', 'Sim, a aula toda.', 'Sim, e fiz mais.'], undefined,
    'Trabalhaste até ao fim?', ['Não.', 'Só um bocado.', 'Sim.', 'Sim, e mais.']),
  'ATI-012|0|0': f('Hoje, o plano mudou. O que fizeste?',
    ['Reclamei.', 'Mudei a reclamar.', 'Aceitei e comecei logo.', 'Aceitei e ajudei a equipa.'], 'Hoje nada mudou.',
    'Mudou o plano. E tu?', ['Reclamei.', 'Mudei a reclamar.', 'Aceitei.', 'Aceitei e ajudei.'], 'Não mudou.'),
  'ATI-012|0|1': f('Hoje, aceitaste a tarefa que te deram?',
    ['Não, quis trocar.', 'Sim, de má vontade.', 'Sim, e fiz bem.', 'Sim, e fiz mais.'], undefined,
    'Aceitaste a tarefa?', ['Não.', 'A reclamar.', 'Sim.', 'Sim, e fiz mais.']),
  'ATI-018|0|0': f('Hoje, um colega estava triste ou sozinho. O que fizeste?',
    ['Gozei ou ignorei.', 'Não fiz nada.', 'Fui falar com ele.', 'Falei e chamei-o para o meu grupo.'], 'Hoje não vi ninguém assim.',
    'Colega sozinho. E tu?', ['Ignorei.', 'Nada.', 'Falei com ele.', 'Chamei-o.'], 'Não vi.'),
  'ATI-018|0|1': f('Hoje, respeitaste o espaço dos colegas?',
    ['Não, fiz barulho ou empurrei.', 'Às vezes incomodei.', 'Sim.', 'Sim, e ajudei um colega a sentir-se bem.'], undefined,
    'Respeitaste os colegas?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, e ajudei.']),
  'ATI-022|0|0': f('Hoje, alguém teve uma ideia diferente. O que fizeste?',
    ['Gozei.', 'Ignorei.', 'Ouvi e respeitei.', 'Ouvi e experimentámos.'], 'Hoje não houve ideias diferentes.',
    'Ideia diferente. E tu?', ['Gozei.', 'Ignorei.', 'Respeitei.', 'Experimentámos.'], 'Não houve.'),
  'ATI-022|0|1': f('Hoje, trabalhaste bem com colegas diferentes de ti?',
    ['Não, gozei ou pus de parte.', 'Evitei trabalhar com eles.', 'Sim, com respeito.', 'Sim, e defendi-os.'], undefined,
    'Trabalhaste com todos?', ['Não.', 'Evitei.', 'Sim.', 'Sim, e defendi.']),
  // ── 3.º ano ──
  'ATI-004|0|0': f('Hoje, acabaste a tarefa. O que fizeste a seguir?',
    ['Fiquei parado.', 'Esperei que me dessem outra.', 'Perguntei o que faltava.', 'Vi o que faltava e comecei.'], 'Hoje a tarefa durou a aula toda.',
    'Acabaste. E depois?', ['Parei.', 'Esperei.', 'Perguntei.', 'Comecei outra.'], 'Não acabei antes.'),
  'ATI-004|0|1': f('Hoje, viste uma coisa por fazer (lixo, loiça). O que fizeste?',
    ['Fingi que não vi.', 'Disse a alguém.', 'Fiz eu.', 'Fiz e combinei com a equipa.'], undefined,
    'Viste lixo ou loiça. E tu?', ['Nada.', 'Disse a alguém.', 'Fiz eu.', 'Fiz e combinei.']),
  'ATI-006|0|0': f('Hoje, não concordaste com alguém. O que fizeste?',
    ['Gritei ou amuei.', 'Fiquei calado.', 'Disse com calma o que pensava.', 'Disse com calma e dei uma solução.'], 'Hoje não discordei de ninguém.',
    'Não concordaste. E tu?', ['Gritei.', 'Calei-me.', 'Disse com calma.', 'Dei uma solução.'], 'Concordei.'),
  'ATI-006|0|1': f('Hoje, como pediste o que precisavas?',
    ['Exigi ou tirei.', 'Não pedi.', 'Pedi com calma.', 'Pedi com calma e agradeci.'], undefined,
    'Como pediste?', ['Tirei.', 'Não pedi.', 'Pedi bem.', 'Pedi e agradeci.']),
  'ATI-014|0|0': f('Hoje, aproveitaste os produtos?',
    ['Deitei comida boa fora.', 'Desperdicei um bocado.', 'Usei o certo e aproveitei.', 'Aproveitei e dei uma ideia.'], 'Hoje não usei produtos.',
    'Desperdiçaste comida?', ['Sim, muita.', 'Um bocado.', 'Não.', 'Não, e dei uma ideia.'], 'Não usei.'),
  'ATI-014|0|1': f('Hoje, poupaste água e luz e separaste o lixo?',
    ['Não.', 'Às vezes.', 'Sim.', 'Sim, e lembrei os colegas.'], undefined,
    'Poupaste água e luz?', ['Não.', 'Às vezes.', 'Sim.', 'Sim, e lembrei.']),
  'ATI-019|0|0': f('Hoje, tiveste uma tarefa nova. O que fizeste?',
    ['Disse que não era capaz.', 'Fiz, mas perguntei tudo.', 'Fiz com confiança.', 'Fiz e mostrei a um colega.'], 'Hoje não tive tarefa nova.',
    'Tarefa nova. E tu?', ['Não fui capaz.', 'Perguntei tudo.', 'Fiz.', 'Fiz e mostrei.'], 'Não tive.'),
  'ATI-019|0|1': f('Hoje, decidiste alguma coisa sozinho/a?',
    ['Não, esperei.', 'Sim, mas perguntei tudo.', 'Sim, sozinho/a.', 'Sim, e expliquei porquê.'], undefined,
    'Decidiste sozinho/a?', ['Não.', 'Com ajuda.', 'Sim.', 'Sim, e expliquei.']),
  'ATI-020|0|0': f('Hoje, o professor deu uma ordem. Como respondeste?',
    ['Refilei ou ignorei.', 'Fiz de má cara.', 'Disse «Sim, chefe» e fiz.', 'Fiz e avisei quando acabei.'], undefined,
    'Deram-te uma ordem. E tu?', ['Refilei.', 'De má cara.', 'Fiz.', 'Fiz e avisei.']),
  'ATI-020|0|1': f('Hoje, portaste-te como numa cozinha a sério?',
    ['Disse palavrões ou cheguei tarde.', 'Falhei uma vez.', 'Sim, com educação.', 'Sim, e fui exemplo.'], undefined,
    'Portaste-te bem?', ['Não.', 'Quase.', 'Sim.', 'Sim, fui exemplo.']),
  'ATI-021|0|0': f('Hoje, viste o trabalho de um colega. O que disseste?',
    ['Gozei.', 'Nada.', 'Disse o que estava bem e o que melhorar.', 'Disse com respeito e dei uma ideia.'], 'Hoje não vi trabalho de colegas.',
    'Trabalho de um colega. Disseste?', ['Gozei.', 'Nada.', 'O bom e o mau.', 'Dei uma ideia.'], 'Não vi.'),
  'ATI-021|0|1': f('No fim, pensaste no teu trabalho?',
    ['Não olhei.', 'Vi que falhou, mas não sei porquê.', 'Sei o que falhou e porquê.', 'Sei o que vou mudar.'], undefined,
    'Pensaste no teu trabalho?', ['Não.', 'Um pouco.', 'Sim.', 'Sim, sei o que mudar.']),
  // ── Eventos e concursos ──
  'EV|ATI-001|0': f('Antes do evento, preparaste-te para a tua tarefa?',
    ['Não, só soube quando cheguei.', 'Pouco, porque mandaram.', 'Sim, sabia a minha tarefa.', 'Sim, e tirei dúvidas antes.'], undefined,
    'Preparaste-te antes?', ['Não.', 'Pouco.', 'Sim.', 'Sim, e perguntei.']),
  'EV|ATI-001|1': f('A que horas chegaste?',
    ['Atrasado, sem avisar.', 'Atrasado, mas avisei.', 'À hora.', 'Antes da hora e ajudei.'], undefined,
    'Chegaste a horas?', ['Não.', 'Avisei.', 'Sim.', 'Antes.']),
  'EV|ATI-003|0': f('Vieste com a farda completa?',
    ['Não.', 'Sim, mas suja.', 'Sim, limpa.', 'Sim, e ajudei um colega.'], undefined,
    'Farda completa?', ['Não.', 'Suja.', 'Sim.', 'Sim, e ajudei.']),
  'EV|ATI-003|1': f('Trouxeste o material?',
    ['Esqueci-me de coisas importantes.', 'Esqueci-me de uma coisa.', 'Trouxe tudo.', 'Trouxe tudo e confirmei.'], undefined,
    'Trouxeste tudo?', ['Não.', 'Quase.', 'Sim.', 'Sim, e confirmei.']),
  'EV|ATI-012|0': f('Uma coisa mudou no evento. O que fizeste?',
    ['Reclamei ou parei.', 'Continuei a reclamar.', 'Adaptei-me.', 'Adaptei-me e ajudei.'], 'Nada mudou.',
    'Mudou. E tu?', ['Parei.', 'Reclamei.', 'Adaptei-me.', 'Ajudei.'], 'Não mudou.'),
  'EV|ATI-012|1': f('Ficaste até ao fim?',
    ['Saí antes.', 'Fiquei, mas não arrumei.', 'Fiquei e arrumei.', 'Fiquei e ajudei os outros.'], undefined,
    'Ficaste até ao fim?', ['Não.', 'Sem arrumar.', 'Sim.', 'Sim, e ajudei.']),
};
