// ════════════════════════════════════════════════════════════════
// REFERENCIAL OFICIAL 811RA144 — Realizações, Critérios de Desempenho
// e Conhecimentos REAIS extraídos do referencial de competências.
//
// Diferente das MICROCOMPETENCIAS (granularidade prática, inventada
// pela ECL para observação em aula — ex: 'Desossar', 'Selar carne'),
// isto é o texto OFICIAL do documento regulamentar, ao nível da UC,
// usado como CONTEXTO — não há correspondência 1-para-1 com as
// microcompetências porque o referencial não desce a esse detalhe.
//
// Usado em: prompt do Guia de Apoio (secção Enquadramento/Competências),
// Recuperação de Módulos (contexto da UC ao gerar perguntas).
// ════════════════════════════════════════════════════════════════

export interface ReferencialUC {
  nome: string;
  realizacoes: string[];
  criteriosDesempenho: string[];
  conhecimentos: string[];
}

export const REFERENCIAL_811RA144: Record<string, ReferencialUC> = {
  UC03576: {
    nome: "Planear e organizar a produção de cozinha",
    realizacoes: ["Elaborar os planos de trabalho.", "Realizar a mise en place.", "Coordenar equipas.", "Acondicionar e conservar os géneros alimentícios e outros produtos."],
    criteriosDesempenho: ["Planear e organizar a produção de cozinha Aplicando e respeitando as regras de organização e funcionamento.", "Coordenando a equipa, assegurando uma comunicação clara e assertiva.", "Assegurando a mise en place e a adequada utilização dos diversos equipamentos e utensílios.", "Garantindo as normas de acondicionamento, armazenamento e conservação das matérias-primas.", "Cumprindo as normas de higiene e segurança alimentar, de segurança e saúde no trabalho."],
    conhecimentos: ["Aplicar as normas e procedimentos de manipulação de alimentos.", "Cortar legumes, vegetais e outros géneros alimentícios.", "Aplicar os procedimentos de controlo de qualidade e estado de frescura.", "Aplicar regras de segurança na utilização de equipamentos e utensílios.", "Aplicar técnicas de limpeza e higienização de equipamentos e utensílios de cozinha.", "Implementar e aplicar as normas de acondicionamento, conservação e armazenamento de géneros alimentícios e outros produtos.", "Preencher a documentação de verificação e controlo de qualidade.", "Identificar os perigos e aplicar medidas preventivas.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC01999: {
    nome: "Preparar e executar confeções de cozinha",
    realizacoes: ["Executar cortes nos diversos géneros alimentícios.", "Executar diversas técnicas de confeção.", "Acondicionar e conservar os produtos preparados."],
    criteriosDesempenho: ["Preparar e executar confeções de cozinha Verificando a frescura e a qualidade dos géneros alimentícios.", "Assegurando a preservação das propriedades dos alimentos e conservação dos produtos preparados.", "Cumprindo as regras de higiene e segurança alimentar, as regras de segurança e saúde no trabalho."],
    conhecimentos: ["Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03577: {
    nome: "Preparar e confecionar molhos e fundos de cozinha",
    realizacoes: ["Elaborar fichas técnicas.", "Preparar a mise en place.", "Preparar e executar confeções de fundos de cozinha.", "Preparar e executar confeções de molhos base de cozinha quentes, frios e seus derivados.", "Acondicionar e conservar matérias-primas e produtos preparados."],
    criteriosDesempenho: ["Preparar e confecionar molhos e fundos de cozinha Composição das manteigas compostas.", "Tecnologia dos equipamentos e utensílios de uma cozinha.", "Equipamentos e utensílios necessários.", "Procedimentos de controlo dos processos de planificação e confeção de fundos de cozinha, molhos e bases.", "Técnicas de preparação e confeção de fundos de cozinha.", "Técnicas de preparação e confeção de molhos base de cozinha quentes e frios e seus derivados.", "Controlo de qualidade do processo de fabrico - preparação, confeção, produtos finais.", "Técnicas de limpeza, desinfeção e controlo de riscos.", "Procedimentos de supervisão;", "Técnicas de empratamento e decoração de produtos confecionados.", "Técnicas de acondicionamento, etiquetagem e conservação de matérias-primas e produtos confecionados.", "Sustentabilidade e economia circular na restauração – âmbito e princípios de circularidade.", "Desperdício na restauração – alimentar, energético, água, embalagens, entre outros.", "-Nomas de higiene e segurança alimentar.", "Normas de segurança e saúde no trabalho."],
    conhecimentos: ["Calcular preços.", "Calcular margens de lucro.", "Controlar custos.", "Redigir fichas técnicas.", "Selecionar e aplicar procedimentos de organização e produção de cozinha.", "Efetuar o planeamento da produção de cozinha.", "Selecionar os equipamentos, ingredientes e utensílios para a confeção de fundos de cozinha e molhos base.", "Selecionar as matérias-primas para a confeção.", "Verificar qualidade e frescura dos ingredientes.", "Aplicar os procedimentos de preparação e confeção de fundos de cozinha.", "Aplicar os procedimentos de preparação e confeção de molhos base de cozinha quentes e frios e seus derivados.", "Aplicar técnicas de empratamento e decoração dos pratos confecionados.", "Aplicar técnicas de acondicionamento, etiquetagem e conservação de produtos confecionados.", "Aplicar técnicas de limpeza e desinfeção.", "Aplicar medidas de redução do desperdício alimentar.", "Cumprir normas de higiene e segurança alimentar.", "Aplicar normas de segurança e saúde no trabalho."],
  },
  UC02002: {
    nome: "Preparar e confecionar acepipes, sopas, entradas, ovos e massas",
    realizacoes: [],
    criteriosDesempenho: ["Preparar e confecionar acepipes, sopas, entradas, ovos e massas Cumprindo as orientações técnicas definidas e o plano de trabalho.", "Considerando a divisão de trabalho pelas brigadas.", "Elaborando fichas técnicas com a informação necessária.", "Garantindo a preservação das propriedades dos alimentos e conservação dos produtos preparados.", "Cumprindo as regras de higiene e segurança alimentar, segurança e saúde no trabalho."],
    conhecimentos: ["Aplicar os procedimentos para a preparação e confeção de acepipes, entradas, pratos de massa e de ovos.", "Aplicar técnicas de empratamento e decoração dos pratos confecionados.", "Aplicar técnicas de acondicionamento, etiquetagem e conservação de produtos confecionados.", "Aplicar técnicas de limpeza e desinfeção.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC02003: {
    nome: "Preparar e confecionar peixes, mariscos e os seus acompanhamentos ou guarnições",
    realizacoes: ["Elaborar fichas técnicas.", "Preparar a mise en place.", "Preparar e executar a confeção de peixes e mariscos.", "Preparar e executar a confeção de acompanhamentos ou guarnições.", "Empratar e decorar os produtos confecionados.", "Acondicionar e conservar matérias-primas e produtos preparados."],
    criteriosDesempenho: ["Preparar e confecionar peixes, mariscos e os seus acompanhamentos ou guarnições Cumprindo as orientações técnicas definidas e o plano de trabalho.", "Considerando a divisão de trabalho pelas brigadas.", "Receituário de confeções de pratos de peixe e marisco.", "Tecnologia dos equipamentos e utensílios de uma cozinha.", "Equipamentos e utensílios necessários.", "Procedimentos de controlo dos processos de planificação e confeção de pratos de peixe e marisco.", "Técnicas de preparação e confeção de pratos de peixe e marisco.", "Técnicas de preparação e confeção de acompanhamentos ou guarnições.", "Controlo de qualidade do processo de fabrico - preparação, confeção, produtos finais.", "Técnicas de limpeza, desinfeção e controlo de riscos.", "Procedimentos de supervisão.", "Técnicas de empratamento e decoração de produtos confecionados.", "Técnicas de acondicionamento, etiquetagem e conservação de matérias-primas e produtos confecionados.", "Sustentabilidade e economia circular na restauração – âmbito e princípios de circularidade.", "Desperdício na restauração – alimentar, energético, água, embalagens, entre outros.", "Normas de higiene e segurança alimentar.", "Normas de segurança e saúde no trabalho."],
    conhecimentos: ["Efetuar pesagens.", "Calcular preços.", "Selecionar e aplicar procedimentos de organização e produção de cozinha.", "Efetuar o planeamento da produção de cozinha.", "Selecionar os equipamentos, ingredientes e utensílios necessários à planificação e confeção de pratos de peixe e marisco.", "Selecionar as matérias-primas para a confeção.", "Verificar qualidade e frescura dos ingredientes.", "Aplicar os procedimentos para a preparação e confeção de pratos de peixe e marisco e respetivas guarnições ou acompanhamentos.", "Aplicar técnicas de empratamento e decoração dos pratos confecionados.", "Aplicar técnicas de acondicionamento, etiquetagem e conservação de produtos confecionados.", "Aplicar técnicas de limpeza e desinfeção.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC02004: {
    nome: "Preparar e confecionar carnes, aves, caça e os seus acompanhamentos ou guarnições",
    realizacoes: ["Elaborar fichas técnicas.", "Preparar a mise en place.", "Preparar e executar confeções de carnes, aves e caça.", "Preparar e executar confeções de acompanhamentos ou guarnições.", "Empratar e decorar os produtos confecionados.", "Acondicionar e conservar os produtos preparados."],
    criteriosDesempenho: ["Preparar e confecionar carnes, aves, caça e os seus acompanhamentos ou guarnições Cumprindo as orientações técnicas definidas e o plano de trabalho.", "Considerando a divisão de trabalho pelas brigadas.", "Elaborando fichas técnicas com a informação necessária.", "Garantindo a preservação das propriedades dos alimentos e conservação dos produtos preparados.", "Cumprindo as regras de higiene e segurança alimentar, segurança e saúde no trabalho."],
    conhecimentos: ["Aplicar técnicas de limpeza e desinfeção.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC02005: {
    nome: "Preparar e confecionar massas base, recheios, cremes e molhos de pastelaria",
    realizacoes: ["Elaborar fichas técnicas.", "Preparar a mise en place.", "Preparar e executar confeções de massas bases de pastelaria.", "Preparar e executar confeções de recheios, cremes base e molhos base de pastelaria.", "Empratar e decorar os produtos confecionados.", "Acondicionar e conservar matérias-primas e produtos preparados."],
    criteriosDesempenho: ["Preparar e confecionar massas base, recheios, cremes e molhos de pastelaria Cumprindo as orientações técnicas definidas e o plano de trabalho.", "Considerando a divisão de trabalho pelas brigadas.", "Garantindo a preservação das propriedades dos alimentos e conservação dos produtos preparados.", "Tecnologia dos equipamentos e utensílios de uma pastelaria.", "Equipamentos e utensílios necessários.", "Procedimentos de controlo dos processos de planificação e confeção de receitas de bases de pastelaria.", "Técnicas de preparação de massas base, recheios, cremes base e molhos base de pastelaria.", "Processos de confeção de massas base, recheios, cremes base e molhos base de pastelaria e aplicações - mise en place, ordem de introdução das matérias-primas, tempo de cozedura e temperatura, textura, acabamento.", "Controlo de qualidade do processo de fabrico - preparação, confeção, produtos finais.", "Técnicas de limpeza, desinfeção e controlo de riscos.", "Procedimentos de supervisão.", "Técnicas de empratamento e decoração de produtos confecionados.", "Técnicas de acondicionamento, etiquetagem e conservação de matérias-primas e produtos.", "Sustentabilidade e economia circular na restauração – âmbito e princípios de circularidade.", "Desperdício na restauração – alimentar, energético, água, embalagens, entre outros.", "Normas de higiene e segurança alimentar.", "Normas de segurança e saúde no trabalho."],
    conhecimentos: ["Selecionar os equipamentos, ingredientes e utensílios necessários à planificação e confeção de receitas de bases de pastelaria.", "Selecionar as matérias-primas para a confeção.", "Verificar a qualidade e frescura dos ingredientes.", "Aplicar os procedimentos para a preparação e confeção de receitas de bases de pastelaria.", "Aplicar técnicas de empratamento e decoração dos produtos de pastelaria confecionados.", "Aplicar técnicas de acondicionamento, etiquetagem e conservação de produtos confecionados.", "Aplicar técnicas de limpeza e desinfeção.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03579: {
    nome: "Gerir aprovisionamentos e controlar custos",
    realizacoes: ["Inventariar e controlar os stocks de géneros alimentícios e o seu estado de conservação.", "Rececionar e armazenar os géneros alimentícios.", "Efetuar e gerir requisições."],
    criteriosDesempenho: ["Gerir aprovisionamentos e controlar custos Realizando a receção de matérias-primas e procedendo ao seu armazenamento:", "Respeitando as regras de rotação de stock e garantindo o estado de conservação das matérias-primas e dos alimentos.", "Cumprindo os procedimentos para a gestão de stocks.", "Cumprindo as regras de higiene e segurança alimentar, segurança e saúde no trabalho."],
    conhecimentos: ["Gestão de stocks e conservação dos produtos.", "Controlo de qualidade dos produtos alimentícios.", "Informática na ótica do utilizador.", "Condições de higiene e segurança alimentar e profissional.", "Preenchimento de documentação física ou em formato digital relativa ao circuito de mercadorias.", "Processos de acondicionamento e conservação de matérias-primas e produtos alimentares.", "Sustentabilidade e economia circular na restauração – âmbito e princípios de circularidade.", "Redução de desperdício alimentar na restauração.", "Processo de inventários.", "Técnicas de rotação de stocks.", "Regras de higiene e segurança alimentar."],
  },
  UC03584: {
    nome: "Implementar regras de higiene e segurança alimentar em hotelaria e restauração",
    realizacoes: [],
    criteriosDesempenho: ["Aplicar as normas de conservação no armazenamento dos alimentos, ao longo de toda a sua duração Limpar e higienizar utensílios, equipamentos e instalações, de acordo com os requisitos gerais e específicos de higiene aplicáveis às instalações do setor alimentar.", "Colaborar na aplicação dos procedimentos de um sistema preventivo de segurança alimentar."],
    conhecimentos: ["Sistema de Análise de Perigos e Controlo de Pontos Críticos (HACCP) – princípios e normas.", "Sistema de Análise de Perigos e Controlo de Pontos Críticos (HACCP) – aplicação.", "Normas de conservação e armazenamento de géneros alimentícios.", "Higiene pessoal, estados de saúde e risco de transmissão de doenças.", "Limpeza, higienização, desinfeção e esterilização - instalações, equipamentos e utensílios.", "Limpeza, higienização, desinfeção e esterilização - processos, etapas e níveis.", "Técnicas de limpeza, desinfeção e controlo de riscos.", "Sustentabilidade e economia circular na restauração – âmbito e princípios de circularidade.", "Desperdício na restauração – alimentar, energético, água, embalagens, entre outros.", "Equipamento de proteção individual (EPI).", "Normas de higiene e segurança alimentar.", "Normas de segurança e saúde no trabalho.", "Normas da qualidade."],
  },
  UC03585: {
    nome: "Conservar matérias-primas alimentares",
    realizacoes: [],
    criteriosDesempenho: ["Conservar matérias-primas alimentares Reconhecendo e confirmando o estado de frescura dos diversos alimentos.", "Adequando as técnicas de preparação e conservação aplicáveis a cada género alimentício.", "Executar o controlo de qualidade."],
    conhecimentos: ["Principais cereais e seus derivados.", "Principais vegetais e frutos, variedades, sazonalidade.", "Ervas aromáticas, condimentos e especiarias.", "Gorduras vegetais e animais.", "Géneros alimentícios de origem animal.", "Carnes de açougue, criação e caça - classificação, variedades, origem, características físicas e nutritivas.", "Peixes e mariscos - classificação, famílias, origem, características físicas e nutritivas.", "Leite - tipos de leite e derivados.", "Ovos - classificação e derivados.", "Controlo de qualidade.", "Estado de frescura.", "Vários tipos de corte de alimentos de origem vegetal e animal.", "Técnicas e procedimentos de conservação.", "Condições de armazenamento - local, temperatura, outros.", "Normas de segurança e higiene alimentar na restauração.", "Normas de higiene e segurança no trabalho."],
  },
  UC03586: {
    nome: "Preparar e confecionar iguarias da cozinha e doçaria tradicional portuguesa",
    realizacoes: ["Elaborar fichas técnicas Preparar a mise en place.", "Preparar e executar confeções de iguarias da cozinha e doçaria tradicional portuguesa.", "Empratar e decorar as iguarias confecionadas.", "Acondicionar e conservar matérias-primas e produtos preparados."],
    criteriosDesempenho: ["Preparar e confecionar iguarias da cozinha e doçaria tradicional portuguesa Cumprindo as orientações técnicas definidas e o plano de trabalho.", "Considerando a divisão de trabalho pelas brigadas.", "Garantindo a preservação das propriedades dos alimentos e conservação dos produtos preparados.", "Cumprindo as regras de higiene e segurança alimentar, segurança e saúde no trabalho."],
    conhecimentos: ["Aplicar técnicas de limpeza e desinfeção.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03587: {
    nome: "Preparar e confecionar pastelaria de sobremesa",
    realizacoes: ["Elaborar fichas técnicas.", "Preparar a mise en place.", "Preparar e executar confeções de pastelaria e doçaria internacional.", "Preparar e executar confeções de produtos de geladaria.", "Empratar e decorar os produtos confecionados.", "Acondicionar e conservar matérias-primas e produtos preparados."],
    criteriosDesempenho: ["Preparar e confecionar pastelaria de sobremesa Cumprindo as orientações técnicas definidas e o plano de trabalho.", "Considerando a divisão de trabalho pelas brigadas.", "Garantindo a preservação das propriedades dos alimentos e conservação dos produtos preparados.", "Cumprindo as regras de higiene e segurança alimentar, segurança e saúde no trabalho."],
    conhecimentos: ["Selecionar as matérias-primas para a confeção.", "Verificar qualidade e frescura dos ingredientes.", "Aplicar os procedimentos para a preparação e confeção de pastelaria internacional e geladaria.", "Aplicar técnicas de empratamento e decoração dos pratos confecionados.", "Aplicar técnicas de acondicionamento, etiquetagem e conservação de produtos confecionados.", "Aplicar técnicas de limpeza e desinfeção.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03588: {
    nome: "Preparar e confecionar iguarias da gastronomia do Mundo",
    realizacoes: ["Elaborar fichas técnicas.", "Preparar a mise en place.", "Preparar e executar confeções de iguarias da cozinha e doçaria internacional.", "Empratar e decorar as iguarias confecionadas.", "Acondicionar e conservar matérias-primas e produtos preparados."],
    criteriosDesempenho: ["Preparar e confecionar iguarias da gastronomia do Mundo Cumprindo as orientações técnicas definidas e o plano de trabalho.", "Considerando a divisão de trabalho pelas brigadas.", "Garantindo a preservação das propriedades dos alimentos e conservação dos produtos preparados.", "Cumprindo as regras de higiene e segurança alimentar, segurança e saúde no trabalho.", "Tecnologia dos equipamentos e utensílios de uma cozinha e pastelaria.", "Equipamentos e utensílios necessários.", "Procedimentos de controlo dos processos de planificação e confeção de pratos e doçaria de diferentes países.", "Técnicas de preparação e confeção de pratos e doçaria de diferentes países.", "Técnicas de preparação e confeção de acompanhamentos ou guarnições.", "Controlo de qualidade do processo de fabrico - preparação, confeção, produtos finais.", "Técnicas de limpeza, desinfeção e controlo de riscos.", "Procedimentos de supervisão.", "Técnicas de empratamento e decoração de produtos confecionados.", "Técnicas de acondicionamento, etiquetagem e conservação de matérias-primas e produtos confecionados.", "Sustentabilidade e economia circular na restauração – âmbito e princípios de circularidade.", "Desperdício na restauração – alimentar, energético, água, embalagens, entre outros.", "Normas de higiene e segurança alimentar.", "Normas de segurança e saúde no trabalho."],
    conhecimentos: ["Calcular preços.", "Selecionar e aplicar procedimentos de organização e produção de cozinha.", "Efetuar o planeamento da produção de cozinha.", "Selecionar os equipamentos, ingredientes e utensílios necessários à planificação e confeção de pratos e doçaria diferentes países.", "Selecionar as matérias-primas para a confeção.", "Verificar qualidade e frescura dos ingredientes.", "Aplicar os procedimentos para a preparação e confeção de pratos e doçaria tradicionais portugueses e respetivas guarnições ou acompanhamentos.", "Aplicar técnicas de empratamento e decoração dos pratos confecionados.", "Aplicar técnicas de acondicionamento, etiquetagem e conservação de produtos confecionados.", "Aplicar técnicas de limpeza e desinfeção.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03589: {
    nome: "Implementar novas tendências na cozinha",
    realizacoes: ["Elaborar fichas técnicas.", "Preparar a mise en place.", "Preparar e confecionar Iguarias da cozinha e doçaria internacionais.", "Empratar e decorar as iguarias confecionadas.", "Acondicionar e conservar matérias-primas e produtos preparados."],
    criteriosDesempenho: ["Implementar novas tendências na cozinha Respeitando as orientações técnicas definidas.", "Aplicando técnicas de limpeza e corte dos ingredientes.", "Assegurando a preservação das propriedades dos alimentos e conservação dos produtos preparados.", "Cumprindo as regras de higiene e segurança alimentar, segurança e saúde no trabalho."],
    conhecimentos: ["Consultar fichas técnicas e receituário.", "Aplicar procedimentos de quantificação de ingredientes.", "Determinar proporções.", "Efetuar pesagens.", "Calcular preços.", "Calcular margens de lucro.", "Controlar custos.", "Selecionar os equipamentos, ingredientes e utensílios necessários à planificação e confeção.", "Aplicar técnicas de empratamento e decoração dos pratos confecionados.", "Aplicar técnicas de acondicionamento, etiquetagem e conservação de produtos confecionados.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03590: {
    nome: "Confecionar produtos sustentáveis",
    realizacoes: ["Explorar os recursos endógenos da região.", "Criar produtos ou propostas inovadoras no âmbito da cozinha sustentável.", "Efetuar o aprovisionamento das matérias-primas, utensílios e materiais."],
    criteriosDesempenho: ["Confecionar produtos sustentáveis Identificando e selecionando os produtos e matérias-primas endógenos.", "Respeitando a agricultura local.", "Cumprindo as regras de segurança e higiene alimentar.", "Dieta mediterrânica - hábitos e culturas alimentares portuguesas.", "Produtos e cozinhas regionais.", "Técnicas e processos culinários - fermentação, maceração, desidratação, outros.", "Tecnologia de matérias-primas.", "Práticas sustentáveis de cozinha.", "Conceito de negócio eco responsável.", "Equipamentos, utensílios necessários, e procedimentos de controlo dos processos de preparação e confeção de cozinha gastronómica sustentável.", "Conceitos de nutrição e dietética.", "Procedimentos de controlo da qualidade.", "Normas de manipulação de alimentos.", "Técnicas de acondicionamento e conservação de matérias-primas e produtos confecionados de cozinha.", "Procedimentos de registo e controlo de stocks.", "Sustentabilidade e economia circular na restauração – âmbito e princípios de circularidade.", "Desperdício na restauração – alimentar, energético, água, embalagens, entre outros.", "Normas de higiene e segurança alimentar.", "Normas de segurança e saúde no trabalho."],
    conhecimentos: ["Aplicar normas de manipulação de alimentos.", "Aplicar técnicas de acondicionamento e conservação de matérias-primas e produtos confecionados de cozinha.", "Aplicar procedimentos de registo e controlo de stocks.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03591: {
    nome: "Planear e executar serviços especiais de cozinha",
    realizacoes: ["Elaborar o plano de trabalho do serviço especial de cozinha.", "Elaborar menus de cozinha para serviços especiais.", "Confecionar as iguarias do serviço especial.", "Cortar e preparar peixes, mariscos, carnes, frutas, doces e queijos.", "Empratar e decorar iguarias.", "Controlar o aprovisionamento das matérias-primas, utensílios e materiais."],
    criteriosDesempenho: ["Planear e executar serviços especiais de cozinha Respeitando as orientações superiores e o plano de produção.", "Elaborando um menu, de acordo com as orientações.", "Cumprindo as regras de organização e funcionamento do serviço de cozinha.", "Considerando a divisão de trabalho pelas brigadas para a realização de serviços especiais.", "Cumprindo as normas de qualidade, segurança e higiene alimentar."],
    conhecimentos: ["Aplicar normas de manipulação de alimentos.", "Aplicar técnicas de acondicionamento e conservação de matérias-primas e produtos confecionados de cozinha.", "Aplicar procedimentos de registo e controlo de stocks.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03592: {
    nome: "Planear e confecionar pastelaria internacional",
    realizacoes: ["Elaborar o plano de trabalho diário e a ficha técnica do produto.", "Confecionar pastelaria internacional.", "Empratar e decorar pastelaria internacional.", "Confecionar especialidades de pastelaria do mundo (francesa, italiana, alemã, outras).", "Empratar e decorar especialidade de pastelaria do mundo.", "Controlar o aprovisionamento das matérias-primas, utensílios e materiais."],
    criteriosDesempenho: ["Planear e confecionar pastelaria internacional Respeitando o plano de produção.", "Cumprindo as regras de organização e funcionamento da secção de cozinha.", "Considerando a divisão de trabalho pelas brigadas.", "Cumprindo as normas de qualidade, segurança e higiene alimentar."],
    conhecimentos: ["Aplicar técnicas de acondicionamento e conservação de matérias-primas, utensílios e materiais de pastelaria.", "Aplicar procedimentos de registo e controlo de stocks.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03593: {
    nome: "Planear e confecionar massas básicas de panificação",
    realizacoes: ["Elaborar o plano de trabalho diário da produção de massas de pão.", "Elaborar a ficha técnica do produto.", "Preparar o local de trabalho, os equipamentos e as matérias-primas.", "Confecionar pão de trigo e respetivas aplicações.", "Confecionar outras massas lêvedas de panificação e respetivas aplicações.", "Confecionar especialidades regionais e respetivas aplicações.", "Efetuar o aprovisionamento dos utensílios, materiais e matérias-primas."],
    criteriosDesempenho: ["Planear e confecionar massas básicas de panificação Respeitando o plano de produção.", "Cumprindo as regras de organização e funcionamento da secção de padaria.", "Considerando a divisão de trabalho pelas brigadas.", "Cumprindo as regras de segurança e higiene alimentar."],
    conhecimentos: [],
  },
  UC03594: {
    nome: "Planear e confecionar Cake Design",
    realizacoes: ["Preparar o local de trabalho, os equipamentos e as matérias-primas.", "Preparar e confecionar a massa e creme para o para o cake design.", "Confecionar os elementos decorativos e decorar o bolo.", "Efetuar o aprovisionamento das matérias-primas, utensílios e materiais."],
    criteriosDesempenho: ["Planear e confecionar Cake Design Respeitando as orientações para a realização do trabalho.", "Cumprindo as normas de qualidade, segurança e higiene alimentar.", "Respeitando os procedimentos de segurança."],
    conhecimentos: ["Aplicar técnicas de acondicionamento e conservação de matérias-primas, utensílios e materiais de pastelaria.", "Aplicar procedimentos de registo e controlo de stocks.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03595: {
    nome: "Planear e confecionar cozinha alternativa",
    realizacoes: ["Elaborar o plano de trabalho diário da produção de cozinha alternativa.", "Elaborar a ficha técnica do produto.", "Preparar o local de trabalho, os equipamentos e as matérias-primas.", "Confecionar pratos de cozinha alternativa.", "Empratar e decorar iguarias de cozinha alternativa.", "Efetuar o aprovisionamento das matérias-primas, utensílios e materiais."],
    criteriosDesempenho: ["Planear e confecionar cozinha alternativa Cumprindo as regras de organização e funcionamento do serviço de cozinha.", "Considerando a divisão de trabalho pelas brigadas.", "Cumprindo as normas de qualidade, segurança e higiene alimentar."],
    conhecimentos: [],
  },
  UC03596: {
    nome: "Planear e confecionar cozinha criativa",
    realizacoes: ["Elaborar o plano de trabalho diário da produção de cozinha criativa.", "Elaborar a ficha técnica do produto.", "Preparar o local de trabalho, os equipamentos e as matérias-primas.", "Confecionar pratos de cozinha criativa.", "Empratar e decorar iguarias de cozinha criativa.", "Efetuar o aprovisionamento das matérias-primas, utensílios e materiais."],
    criteriosDesempenho: ["Processos e tempos de confeção.", "Procedimentos de quantificação de ingredientes, proporções e pesagens.", "Técnicas de cálculo de preços.", "Procedimentos de manipulação de alimentos.", "Noções de higiene e desinfeção.", "Técnicas de preparação e confeção de cozinha criativa - confeção a vácuo, confeção a baixas temperaturas, outras.", "Equipamentos, utensílios necessários e procedimentos de controlo dos processos de preparação e confeção de cozinha criativa.", "Técnicas de empratamento.", "Processos de decoração de cozinha criativa.", "Equipamentos e utensílios necessários e procedimentos de controlo dos processos de empratamento e decoração da cozinha criativa.", "Procedimentos de controlo da qualidade.", "Técnicas de acondicionamento e conservação de matérias-primas e produtos confecionados de cozinha.", "Procedimentos de registo e controlo de stocks.", "Sustentabilidade e economia circular na restauração – âmbito e princípios de circularidade.", "Desperdício na restauração – alimentar, energético, água, embalagens, entre outros.", "Normas de higiene e segurança alimentar.", "Normas de segurança e saúde no trabalho."],
    conhecimentos: ["Selecionar e aplicar as técnicas de preparação de cozinha criativa.", "Organizar o espaço, os equipamentos e os utensílios.", "Aplicar os procedimentos para a confeção de cozinha criativa.", "Aplicar as técnicas de empratamento de cozinha criativa.", "Aplicar os processos de decoração de cozinha criativa.", "Aplicar normas de manipulação de alimentos.", "Acondicionar e conservar matérias- primas e produtos confecionados de cozinha.", "Registar e controlo stocks.", "Aplicar medidas de redução do desperdício alimentar.", "Aplicar as normas de higiene e segurança alimentar.", "Aplicar as normas de segurança e saúde no trabalho."],
  },
  UC03597: {
    nome: "Planear e confecionar massas especiais de panificação",
    realizacoes: ["Elaborar o plano de trabalho diário da produção de massas especiais.", "Elaborar a ficha técnica do produto.", "Preparar o local de trabalho, os equipamentos e as matérias-primas.", "Confecionar pão especial de trigo e respetivas aplicações.", "Confecionar massas de pão especiais.", "Efetuar o aprovisionamento dos utensílios, materiais e matérias-primas."],
    criteriosDesempenho: ["Planear e confecionar massas especiais de panificação Cumprindo as regras de organização e funcionamento do serviço de cozinha.", "Considerando a divisão de trabalho pelas brigadas.", "Cumprindo as normas de qualidade, segurança e higiene alimentar."],
    conhecimentos: ["Dispositivos tecnológicos com acesso à internet.", "Código de boas práticas para uma restauração circular e sustentável.", "Restaurante/Bar"],
  },
};

export function getReferencialUC(ucId: string): ReferencialUC | undefined {
  return REFERENCIAL_811RA144[ucId];
}
