// ============================================================
// Frases de autoavaliação — SUBTÉCNICAS (S001-S213)
// Fórmula adaptada: 4 níveis (não consegui / com ajuda / consegui / com autonomia)
// ============================================================

import { FrasesCompetencia } from './frases_atitudes';

export const FRASES_SUBTECNICAS: FrasesCompetencia[] = [
  { competenciaId: 'S001', frases: [
    'Não consegui elaborar o plano de produção / trabalho de forma correta, precisei de ajuda constante.',
    'Consegui elaborar o plano de produção / trabalho, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui elaborar o plano de produção / trabalho corretamente, sem erros relevantes.',
    'Consegui elaborar o plano de produção / trabalho com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S002', frases: [
    'Não consegui consultar fichas técnicas e receitas de forma correta, precisei de ajuda constante.',
    'Consegui consultar fichas técnicas e receitas, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui consultar fichas técnicas e receitas corretamente, sem erros relevantes.',
    'Consegui consultar fichas técnicas e receitas com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S003', frases: [
    'Não consegui realizar a mise en place de forma correta, precisei de ajuda constante.',
    'Consegui realizar a mise en place, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui realizar a mise en place corretamente, sem erros relevantes.',
    'Consegui realizar a mise en place com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S004', frases: [
    'Não consegui organizar o posto de trabalho / bancada de forma correta, precisei de ajuda constante.',
    'Consegui organizar o posto de trabalho / bancada, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui organizar o posto de trabalho / bancada corretamente, sem erros relevantes.',
    'Consegui organizar o posto de trabalho / bancada com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S005', frases: [
    'Não consegui organizar a brigada e distribuir tarefas de forma correta, precisei de ajuda constante.',
    'Consegui organizar a brigada e distribuir tarefas, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui organizar a brigada e distribuir tarefas corretamente, sem erros relevantes.',
    'Consegui organizar a brigada e distribuir tarefas com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S006', frases: [
    'Não consegui preparar e manusear equipamentos e utensílios de forma correta, precisei de ajuda constante.',
    'Consegui preparar e manusear equipamentos e utensílios, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar e manusear equipamentos e utensílios corretamente, sem erros relevantes.',
    'Consegui preparar e manusear equipamentos e utensílios com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S007', frases: [
    'Não consegui dosear e pesar ingredientes (capitação) de forma correta, precisei de ajuda constante.',
    'Consegui dosear e pesar ingredientes (capitação), mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui dosear e pesar ingredientes (capitação) corretamente, sem erros relevantes.',
    'Consegui dosear e pesar ingredientes (capitação) com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S008', frases: [
    'Não consegui porcionar alimentos de forma correta, precisei de ajuda constante.',
    'Consegui porcionar alimentos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui porcionar alimentos corretamente, sem erros relevantes.',
    'Consegui porcionar alimentos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S010', frases: [
    'Não consegui rececionar mercadorias de forma correta, precisei de ajuda constante.',
    'Consegui rececionar mercadorias, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui rececionar mercadorias corretamente, sem erros relevantes.',
    'Consegui rececionar mercadorias com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S011', frases: [
    'Não consegui verificar temperatura de receção de forma correta, precisei de ajuda constante.',
    'Consegui verificar temperatura de receção, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui verificar temperatura de receção corretamente, sem erros relevantes.',
    'Consegui verificar temperatura de receção com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S012', frases: [
    'Não consegui verificar validade e integridade das embalagens de forma correta, precisei de ajuda constante.',
    'Consegui verificar validade e integridade das embalagens, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui verificar validade e integridade das embalagens corretamente, sem erros relevantes.',
    'Consegui verificar validade e integridade das embalagens com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S013', frases: [
    'Não consegui verificar o estado de frescura dos produtos de forma correta, precisei de ajuda constante.',
    'Consegui verificar o estado de frescura dos produtos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui verificar o estado de frescura dos produtos corretamente, sem erros relevantes.',
    'Consegui verificar o estado de frescura dos produtos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S014', frases: [
    'Não consegui armazenar e rotular produtos (FIFO/FEFO) de forma correta, precisei de ajuda constante.',
    'Consegui armazenar e rotular produtos (FIFO/FEFO), mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui armazenar e rotular produtos (FIFO/FEFO) corretamente, sem erros relevantes.',
    'Consegui armazenar e rotular produtos (FIFO/FEFO) com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S015', frases: [
    'Não consegui acondicionar, conservar, refrigerar e congelar produtos de forma correta, precisei de ajuda constante.',
    'Consegui acondicionar, conservar, refrigerar e congelar produtos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui acondicionar, conservar, refrigerar e congelar produtos corretamente, sem erros relevantes.',
    'Consegui acondicionar, conservar, refrigerar e congelar produtos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S016', frases: [
    'Não consegui regenerar alimentos de forma correta, precisei de ajuda constante.',
    'Consegui regenerar alimentos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui regenerar alimentos corretamente, sem erros relevantes.',
    'Consegui regenerar alimentos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S017', frases: [
    'Não consegui abater temperatura de forma correta, precisei de ajuda constante.',
    'Consegui abater temperatura, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui abater temperatura corretamente, sem erros relevantes.',
    'Consegui abater temperatura com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S020', frases: [
    'Não consegui lavar vegetais de forma correta, precisei de ajuda constante.',
    'Consegui lavar vegetais, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui lavar vegetais corretamente, sem erros relevantes.',
    'Consegui lavar vegetais com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S021', frases: [
    'Não consegui desinfetar vegetais de forma correta, precisei de ajuda constante.',
    'Consegui desinfetar vegetais, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui desinfetar vegetais corretamente, sem erros relevantes.',
    'Consegui desinfetar vegetais com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S022', frases: [
    'Não consegui descascar legumes de forma correta, precisei de ajuda constante.',
    'Consegui descascar legumes, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui descascar legumes corretamente, sem erros relevantes.',
    'Consegui descascar legumes com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S023', frases: [
    'Não consegui tornear legumes de forma correta, precisei de ajuda constante.',
    'Consegui tornear legumes, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui tornear legumes corretamente, sem erros relevantes.',
    'Consegui tornear legumes com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S024', frases: [
    'Não consegui cortar legumes de forma correta, precisei de ajuda constante.',
    'Consegui cortar legumes, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar legumes corretamente, sem erros relevantes.',
    'Consegui cortar legumes com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S025', frases: [
    'Não consegui cortar fruta de forma correta, precisei de ajuda constante.',
    'Consegui cortar fruta, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar fruta corretamente, sem erros relevantes.',
    'Consegui cortar fruta com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S026', frases: [
    'Não consegui preparar ervas aromáticas e especiarias de forma correta, precisei de ajuda constante.',
    'Consegui preparar ervas aromáticas e especiarias, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar ervas aromáticas e especiarias corretamente, sem erros relevantes.',
    'Consegui preparar ervas aromáticas e especiarias com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S030', frases: [
    'Não consegui escamar peixe de forma correta, precisei de ajuda constante.',
    'Consegui escamar peixe, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui escamar peixe corretamente, sem erros relevantes.',
    'Consegui escamar peixe com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S031', frases: [
    'Não consegui eviscerar peixe de forma correta, precisei de ajuda constante.',
    'Consegui eviscerar peixe, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui eviscerar peixe corretamente, sem erros relevantes.',
    'Consegui eviscerar peixe com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S032', frases: [
    'Não consegui filetar peixe de forma correta, precisei de ajuda constante.',
    'Consegui filetar peixe, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui filetar peixe corretamente, sem erros relevantes.',
    'Consegui filetar peixe com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S033', frases: [
    'Não consegui retirar espinhas / despinhar de forma correta, precisei de ajuda constante.',
    'Consegui retirar espinhas / despinhar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui retirar espinhas / despinhar corretamente, sem erros relevantes.',
    'Consegui retirar espinhas / despinhar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S034', frases: [
    'Não consegui porcionar peixe de forma correta, precisei de ajuda constante.',
    'Consegui porcionar peixe, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui porcionar peixe corretamente, sem erros relevantes.',
    'Consegui porcionar peixe com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S035', frases: [
    'Não consegui preparar marisco de forma correta, precisei de ajuda constante.',
    'Consegui preparar marisco, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar marisco corretamente, sem erros relevantes.',
    'Consegui preparar marisco com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S036', frases: [
    'Não consegui marinar peixe de forma correta, precisei de ajuda constante.',
    'Consegui marinar peixe, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui marinar peixe corretamente, sem erros relevantes.',
    'Consegui marinar peixe com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S040', frases: [
    'Não consegui aparar carne de forma correta, precisei de ajuda constante.',
    'Consegui aparar carne, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui aparar carne corretamente, sem erros relevantes.',
    'Consegui aparar carne com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S041', frases: [
    'Não consegui desossar carne de forma correta, precisei de ajuda constante.',
    'Consegui desossar carne, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui desossar carne corretamente, sem erros relevantes.',
    'Consegui desossar carne com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S042', frases: [
    'Não consegui atar carne de forma correta, precisei de ajuda constante.',
    'Consegui atar carne, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui atar carne corretamente, sem erros relevantes.',
    'Consegui atar carne com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S043', frases: [
    'Não consegui porcionar carne de forma correta, precisei de ajuda constante.',
    'Consegui porcionar carne, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui porcionar carne corretamente, sem erros relevantes.',
    'Consegui porcionar carne com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S044', frases: [
    'Não consegui preparar aves de forma correta, precisei de ajuda constante.',
    'Consegui preparar aves, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar aves corretamente, sem erros relevantes.',
    'Consegui preparar aves com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S045', frases: [
    'Não consegui preparar caça de forma correta, precisei de ajuda constante.',
    'Consegui preparar caça, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar caça corretamente, sem erros relevantes.',
    'Consegui preparar caça com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S046', frases: [
    'Não consegui preparar ovos de forma correta, precisei de ajuda constante.',
    'Consegui preparar ovos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar ovos corretamente, sem erros relevantes.',
    'Consegui preparar ovos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S047', frases: [
    'Não consegui marinar carne de forma correta, precisei de ajuda constante.',
    'Consegui marinar carne, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui marinar carne corretamente, sem erros relevantes.',
    'Consegui marinar carne com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S048', frases: [
    'Não consegui lardear / bardar carne de forma correta, precisei de ajuda constante.',
    'Consegui lardear / bardar carne, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui lardear / bardar carne corretamente, sem erros relevantes.',
    'Consegui lardear / bardar carne com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S050', frases: [
    'Não consegui cortar em juliana de forma correta, precisei de ajuda constante.',
    'Consegui cortar em juliana, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar em juliana corretamente, sem erros relevantes.',
    'Consegui cortar em juliana com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S051', frases: [
    'Não consegui cortar em brunoise de forma correta, precisei de ajuda constante.',
    'Consegui cortar em brunoise, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar em brunoise corretamente, sem erros relevantes.',
    'Consegui cortar em brunoise com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S052', frases: [
    'Não consegui cortar em macedoine de forma correta, precisei de ajuda constante.',
    'Consegui cortar em macedoine, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar em macedoine corretamente, sem erros relevantes.',
    'Consegui cortar em macedoine com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S053', frases: [
    'Não consegui cortar em jardineira de forma correta, precisei de ajuda constante.',
    'Consegui cortar em jardineira, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar em jardineira corretamente, sem erros relevantes.',
    'Consegui cortar em jardineira com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S054', frases: [
    'Não consegui cortar em mirepoix de forma correta, precisei de ajuda constante.',
    'Consegui cortar em mirepoix, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar em mirepoix corretamente, sem erros relevantes.',
    'Consegui cortar em mirepoix com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S055', frases: [
    'Não consegui cortar em paysanne de forma correta, precisei de ajuda constante.',
    'Consegui cortar em paysanne, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar em paysanne corretamente, sem erros relevantes.',
    'Consegui cortar em paysanne com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S056', frases: [
    'Não consegui cortar em chiffonade de forma correta, precisei de ajuda constante.',
    'Consegui cortar em chiffonade, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar em chiffonade corretamente, sem erros relevantes.',
    'Consegui cortar em chiffonade com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S057', frases: [
    'Não consegui fazer concassé de tomate de forma correta, precisei de ajuda constante.',
    'Consegui fazer concassé de tomate, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui fazer concassé de tomate corretamente, sem erros relevantes.',
    'Consegui fazer concassé de tomate com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S058', frases: [
    'Não consegui cortar em rodelas / gomos / bastões / cubos de forma correta, precisei de ajuda constante.',
    'Consegui cortar em rodelas / gomos / bastões / cubos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar em rodelas / gomos / bastões / cubos corretamente, sem erros relevantes.',
    'Consegui cortar em rodelas / gomos / bastões / cubos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S059', frases: [
    'Não consegui laminar ingredientes de forma correta, precisei de ajuda constante.',
    'Consegui laminar ingredientes, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui laminar ingredientes corretamente, sem erros relevantes.',
    'Consegui laminar ingredientes com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S060', frases: [
    'Não consegui picar ingredientes de forma correta, precisei de ajuda constante.',
    'Consegui picar ingredientes, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui picar ingredientes corretamente, sem erros relevantes.',
    'Consegui picar ingredientes com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S061', frases: [
    'Não consegui cortar batata palito de forma correta, precisei de ajuda constante.',
    'Consegui cortar batata palito, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar batata palito corretamente, sem erros relevantes.',
    'Consegui cortar batata palito com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S062', frases: [
    'Não consegui cortar batata chips de forma correta, precisei de ajuda constante.',
    'Consegui cortar batata chips, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar batata chips corretamente, sem erros relevantes.',
    'Consegui cortar batata chips com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S063', frases: [
    'Não consegui cortar batata ponte nova de forma correta, precisei de ajuda constante.',
    'Consegui cortar batata ponte nova, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cortar batata ponte nova corretamente, sem erros relevantes.',
    'Consegui cortar batata ponte nova com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S064', frases: [
    'Não consegui preparar batata noisette de forma correta, precisei de ajuda constante.',
    'Consegui preparar batata noisette, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar batata noisette corretamente, sem erros relevantes.',
    'Consegui preparar batata noisette com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S070', frases: [
    'Não consegui preparar fundo branco de forma correta, precisei de ajuda constante.',
    'Consegui preparar fundo branco, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar fundo branco corretamente, sem erros relevantes.',
    'Consegui preparar fundo branco com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S071', frases: [
    'Não consegui preparar fundo escuro de forma correta, precisei de ajuda constante.',
    'Consegui preparar fundo escuro, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar fundo escuro corretamente, sem erros relevantes.',
    'Consegui preparar fundo escuro com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S072', frases: [
    'Não consegui preparar fumet (fundo de peixe) de forma correta, precisei de ajuda constante.',
    'Consegui preparar fumet (fundo de peixe), mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar fumet (fundo de peixe) corretamente, sem erros relevantes.',
    'Consegui preparar fumet (fundo de peixe) com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S073', frases: [
    'Não consegui preparar consommé de forma correta, precisei de ajuda constante.',
    'Consegui preparar consommé, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar consommé corretamente, sem erros relevantes.',
    'Consegui preparar consommé com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S074', frases: [
    'Não consegui preparar velouté de forma correta, precisei de ajuda constante.',
    'Consegui preparar velouté, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar velouté corretamente, sem erros relevantes.',
    'Consegui preparar velouté com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S075', frases: [
    'Não consegui preparar béchamel de forma correta, precisei de ajuda constante.',
    'Consegui preparar béchamel, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar béchamel corretamente, sem erros relevantes.',
    'Consegui preparar béchamel com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S076', frases: [
    'Não consegui preparar molho espanhol de forma correta, precisei de ajuda constante.',
    'Consegui preparar molho espanhol, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar molho espanhol corretamente, sem erros relevantes.',
    'Consegui preparar molho espanhol com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S077', frases: [
    'Não consegui preparar molho de tomate de forma correta, precisei de ajuda constante.',
    'Consegui preparar molho de tomate, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar molho de tomate corretamente, sem erros relevantes.',
    'Consegui preparar molho de tomate com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S078', frases: [
    'Não consegui preparar molho holandês de forma correta, precisei de ajuda constante.',
    'Consegui preparar molho holandês, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar molho holandês corretamente, sem erros relevantes.',
    'Consegui preparar molho holandês com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S079', frases: [
    'Não consegui preparar maionese / vinagrete de forma correta, precisei de ajuda constante.',
    'Consegui preparar maionese / vinagrete, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar maionese / vinagrete corretamente, sem erros relevantes.',
    'Consegui preparar maionese / vinagrete com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S080', frases: [
    'Não consegui preparar roux / beurre manié de forma correta, precisei de ajuda constante.',
    'Consegui preparar roux / beurre manié, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar roux / beurre manié corretamente, sem erros relevantes.',
    'Consegui preparar roux / beurre manié com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S081', frases: [
    'Não consegui emulsionar molho de forma correta, precisei de ajuda constante.',
    'Consegui emulsionar molho, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui emulsionar molho corretamente, sem erros relevantes.',
    'Consegui emulsionar molho com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S082', frases: [
    'Não consegui reduzir molho de forma correta, precisei de ajuda constante.',
    'Consegui reduzir molho, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui reduzir molho corretamente, sem erros relevantes.',
    'Consegui reduzir molho com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S083', frases: [
    'Não consegui ligar molho de forma correta, precisei de ajuda constante.',
    'Consegui ligar molho, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui ligar molho corretamente, sem erros relevantes.',
    'Consegui ligar molho com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S084', frases: [
    'Não consegui montar molho com manteiga de forma correta, precisei de ajuda constante.',
    'Consegui montar molho com manteiga, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui montar molho com manteiga corretamente, sem erros relevantes.',
    'Consegui montar molho com manteiga com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S085', frases: [
    'Não consegui afinar / retificar temperos de forma correta, precisei de ajuda constante.',
    'Consegui afinar / retificar temperos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui afinar / retificar temperos corretamente, sem erros relevantes.',
    'Consegui afinar / retificar temperos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S086', frases: [
    'Não consegui desglasar de forma correta, precisei de ajuda constante.',
    'Consegui desglasar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui desglasar corretamente, sem erros relevantes.',
    'Consegui desglasar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S087', frases: [
    'Não consegui aromatizar / infusionar de forma correta, precisei de ajuda constante.',
    'Consegui aromatizar / infusionar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui aromatizar / infusionar corretamente, sem erros relevantes.',
    'Consegui aromatizar / infusionar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S090', frases: [
    'Não consegui cozer em água de forma correta, precisei de ajuda constante.',
    'Consegui cozer em água, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cozer em água corretamente, sem erros relevantes.',
    'Consegui cozer em água com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S091', frases: [
    'Não consegui cozer a vapor de forma correta, precisei de ajuda constante.',
    'Consegui cozer a vapor, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cozer a vapor corretamente, sem erros relevantes.',
    'Consegui cozer a vapor com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S092', frases: [
    'Não consegui escalfar de forma correta, precisei de ajuda constante.',
    'Consegui escalfar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui escalfar corretamente, sem erros relevantes.',
    'Consegui escalfar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S093', frases: [
    'Não consegui escaldar e branquear de forma correta, precisei de ajuda constante.',
    'Consegui escaldar e branquear, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui escaldar e branquear corretamente, sem erros relevantes.',
    'Consegui escaldar e branquear com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S094', frases: [
    'Não consegui refogar de forma correta, precisei de ajuda constante.',
    'Consegui refogar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui refogar corretamente, sem erros relevantes.',
    'Consegui refogar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S095', frases: [
    'Não consegui saltear de forma correta, precisei de ajuda constante.',
    'Consegui saltear, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui saltear corretamente, sem erros relevantes.',
    'Consegui saltear com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S096', frases: [
    'Não consegui suar de forma correta, precisei de ajuda constante.',
    'Consegui suar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui suar corretamente, sem erros relevantes.',
    'Consegui suar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S097', frases: [
    'Não consegui estufar de forma correta, precisei de ajuda constante.',
    'Consegui estufar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui estufar corretamente, sem erros relevantes.',
    'Consegui estufar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S098', frases: [
    'Não consegui guisar de forma correta, precisei de ajuda constante.',
    'Consegui guisar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui guisar corretamente, sem erros relevantes.',
    'Consegui guisar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S099', frases: [
    'Não consegui brasear de forma correta, precisei de ajuda constante.',
    'Consegui brasear, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui brasear corretamente, sem erros relevantes.',
    'Consegui brasear com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S100', frases: [
    'Não consegui grelhar de forma correta, precisei de ajuda constante.',
    'Consegui grelhar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui grelhar corretamente, sem erros relevantes.',
    'Consegui grelhar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S101', frases: [
    'Não consegui assar de forma correta, precisei de ajuda constante.',
    'Consegui assar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui assar corretamente, sem erros relevantes.',
    'Consegui assar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S102', frases: [
    'Não consegui gratinar de forma correta, precisei de ajuda constante.',
    'Consegui gratinar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui gratinar corretamente, sem erros relevantes.',
    'Consegui gratinar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S103', frases: [
    'Não consegui selar carne de forma correta, precisei de ajuda constante.',
    'Consegui selar carne, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui selar carne corretamente, sem erros relevantes.',
    'Consegui selar carne com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S104', frases: [
    'Não consegui fritar peixe de forma correta, precisei de ajuda constante.',
    'Consegui fritar peixe, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui fritar peixe corretamente, sem erros relevantes.',
    'Consegui fritar peixe com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S105', frases: [
    'Não consegui fritar carne / produtos panados de forma correta, precisei de ajuda constante.',
    'Consegui fritar carne / produtos panados, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui fritar carne / produtos panados corretamente, sem erros relevantes.',
    'Consegui fritar carne / produtos panados com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S106', frases: [
    'Não consegui fritar batatas e controlar temperatura de fritura de forma correta, precisei de ajuda constante.',
    'Consegui fritar batatas e controlar temperatura de fritura, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui fritar batatas e controlar temperatura de fritura corretamente, sem erros relevantes.',
    'Consegui fritar batatas e controlar temperatura de fritura com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S107', frases: [
    'Não consegui confitar de forma correta, precisei de ajuda constante.',
    'Consegui confitar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui confitar corretamente, sem erros relevantes.',
    'Consegui confitar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S108', frases: [
    'Não consegui fumar / desidratar de forma correta, precisei de ajuda constante.',
    'Consegui fumar / desidratar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui fumar / desidratar corretamente, sem erros relevantes.',
    'Consegui fumar / desidratar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S109', frases: [
    'Não consegui cozinhar a baixa temperatura / sous-vide de forma correta, precisei de ajuda constante.',
    'Consegui cozinhar a baixa temperatura / sous-vide, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cozinhar a baixa temperatura / sous-vide corretamente, sem erros relevantes.',
    'Consegui cozinhar a baixa temperatura / sous-vide com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S110', frases: [
    'Não consegui caramelizar de forma correta, precisei de ajuda constante.',
    'Consegui caramelizar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui caramelizar corretamente, sem erros relevantes.',
    'Consegui caramelizar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S111', frases: [
    'Não consegui flambar de forma correta, precisei de ajuda constante.',
    'Consegui flambar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui flambar corretamente, sem erros relevantes.',
    'Consegui flambar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S112', frases: [
    'Não consegui tostar / dourar de forma correta, precisei de ajuda constante.',
    'Consegui tostar / dourar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui tostar / dourar corretamente, sem erros relevantes.',
    'Consegui tostar / dourar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S120', frases: [
    'Não consegui preparar sopa de forma correta, precisei de ajuda constante.',
    'Consegui preparar sopa, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar sopa corretamente, sem erros relevantes.',
    'Consegui preparar sopa com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S121', frases: [
    'Não consegui preparar creme / aveludado / puré de forma correta, precisei de ajuda constante.',
    'Consegui preparar creme / aveludado / puré, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar creme / aveludado / puré corretamente, sem erros relevantes.',
    'Consegui preparar creme / aveludado / puré com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S122', frases: [
    'Não consegui preparar entrada fria ou quente de forma correta, precisei de ajuda constante.',
    'Consegui preparar entrada fria ou quente, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar entrada fria ou quente corretamente, sem erros relevantes.',
    'Consegui preparar entrada fria ou quente com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S123', frases: [
    'Não consegui preparar acepipe de forma correta, precisei de ajuda constante.',
    'Consegui preparar acepipe, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar acepipe corretamente, sem erros relevantes.',
    'Consegui preparar acepipe com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S130', frases: [
    'Não consegui preparar ovos mexidos de forma correta, precisei de ajuda constante.',
    'Consegui preparar ovos mexidos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar ovos mexidos corretamente, sem erros relevantes.',
    'Consegui preparar ovos mexidos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S131', frases: [
    'Não consegui preparar omelete de forma correta, precisei de ajuda constante.',
    'Consegui preparar omelete, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar omelete corretamente, sem erros relevantes.',
    'Consegui preparar omelete com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S132', frases: [
    'Não consegui preparar ovo escalfado / cozido de forma correta, precisei de ajuda constante.',
    'Consegui preparar ovo escalfado / cozido, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar ovo escalfado / cozido corretamente, sem erros relevantes.',
    'Consegui preparar ovo escalfado / cozido com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S133', frases: [
    'Não consegui preparar massa fresca / recheada de forma correta, precisei de ajuda constante.',
    'Consegui preparar massa fresca / recheada, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar massa fresca / recheada corretamente, sem erros relevantes.',
    'Consegui preparar massa fresca / recheada com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S134', frases: [
    'Não consegui cozer massa al dente de forma correta, precisei de ajuda constante.',
    'Consegui cozer massa al dente, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui cozer massa al dente corretamente, sem erros relevantes.',
    'Consegui cozer massa al dente com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S135', frases: [
    'Não consegui preparar risotto de forma correta, precisei de ajuda constante.',
    'Consegui preparar risotto, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar risotto corretamente, sem erros relevantes.',
    'Consegui preparar risotto com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S140', frases: [
    'Não consegui confecionar peixe de forma correta, precisei de ajuda constante.',
    'Consegui confecionar peixe, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui confecionar peixe corretamente, sem erros relevantes.',
    'Consegui confecionar peixe com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S141', frases: [
    'Não consegui confecionar marisco de forma correta, precisei de ajuda constante.',
    'Consegui confecionar marisco, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui confecionar marisco corretamente, sem erros relevantes.',
    'Consegui confecionar marisco com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S142', frases: [
    'Não consegui preparar guarnições para peixe/marisco de forma correta, precisei de ajuda constante.',
    'Consegui preparar guarnições para peixe/marisco, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar guarnições para peixe/marisco corretamente, sem erros relevantes.',
    'Consegui preparar guarnições para peixe/marisco com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S143', frases: [
    'Não consegui empratar peixe e marisco de forma correta, precisei de ajuda constante.',
    'Consegui empratar peixe e marisco, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui empratar peixe e marisco corretamente, sem erros relevantes.',
    'Consegui empratar peixe e marisco com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S150', frases: [
    'Não consegui confecionar carne, aves ou caça de forma correta, precisei de ajuda constante.',
    'Consegui confecionar carne, aves ou caça, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui confecionar carne, aves ou caça corretamente, sem erros relevantes.',
    'Consegui confecionar carne, aves ou caça com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S151', frases: [
    'Não consegui preparar molhos para carne/aves/caça de forma correta, precisei de ajuda constante.',
    'Consegui preparar molhos para carne/aves/caça, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar molhos para carne/aves/caça corretamente, sem erros relevantes.',
    'Consegui preparar molhos para carne/aves/caça com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S152', frases: [
    'Não consegui preparar guarnições para carne de forma correta, precisei de ajuda constante.',
    'Consegui preparar guarnições para carne, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar guarnições para carne corretamente, sem erros relevantes.',
    'Consegui preparar guarnições para carne com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S153', frases: [
    'Não consegui empratar carne, aves ou caça de forma correta, precisei de ajuda constante.',
    'Consegui empratar carne, aves ou caça, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui empratar carne, aves ou caça corretamente, sem erros relevantes.',
    'Consegui empratar carne, aves ou caça com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S154', frases: [
    'Não consegui trinchar carne ou aves de forma correta, precisei de ajuda constante.',
    'Consegui trinchar carne ou aves, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui trinchar carne ou aves corretamente, sem erros relevantes.',
    'Consegui trinchar carne ou aves com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S160', frases: [
    'Não consegui preparar massa areada de forma correta, precisei de ajuda constante.',
    'Consegui preparar massa areada, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar massa areada corretamente, sem erros relevantes.',
    'Consegui preparar massa areada com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S161', frases: [
    'Não consegui preparar massa folhada / laminar de forma correta, precisei de ajuda constante.',
    'Consegui preparar massa folhada / laminar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar massa folhada / laminar corretamente, sem erros relevantes.',
    'Consegui preparar massa folhada / laminar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S162', frases: [
    'Não consegui preparar massa lêveda / brioche de forma correta, precisei de ajuda constante.',
    'Consegui preparar massa lêveda / brioche, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar massa lêveda / brioche corretamente, sem erros relevantes.',
    'Consegui preparar massa lêveda / brioche com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S163', frases: [
    'Não consegui preparar pâte à choux de forma correta, precisei de ajuda constante.',
    'Consegui preparar pâte à choux, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar pâte à choux corretamente, sem erros relevantes.',
    'Consegui preparar pâte à choux com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S164', frases: [
    'Não consegui preparar creme pasteleiro de forma correta, precisei de ajuda constante.',
    'Consegui preparar creme pasteleiro, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar creme pasteleiro corretamente, sem erros relevantes.',
    'Consegui preparar creme pasteleiro com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S165', frases: [
    'Não consegui preparar creme inglês de forma correta, precisei de ajuda constante.',
    'Consegui preparar creme inglês, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar creme inglês corretamente, sem erros relevantes.',
    'Consegui preparar creme inglês com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S166', frases: [
    'Não consegui preparar ganache de forma correta, precisei de ajuda constante.',
    'Consegui preparar ganache, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar ganache corretamente, sem erros relevantes.',
    'Consegui preparar ganache com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S167', frases: [
    'Não consegui preparar merengue de forma correta, precisei de ajuda constante.',
    'Consegui preparar merengue, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar merengue corretamente, sem erros relevantes.',
    'Consegui preparar merengue com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S168', frases: [
    'Não consegui preparar sabayon de forma correta, precisei de ajuda constante.',
    'Consegui preparar sabayon, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar sabayon corretamente, sem erros relevantes.',
    'Consegui preparar sabayon com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S169', frases: [
    'Não consegui temperar chocolate de forma correta, precisei de ajuda constante.',
    'Consegui temperar chocolate, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui temperar chocolate corretamente, sem erros relevantes.',
    'Consegui temperar chocolate com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S170', frases: [
    'Não consegui preparar recheios e coberturas de forma correta, precisei de ajuda constante.',
    'Consegui preparar recheios e coberturas, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar recheios e coberturas corretamente, sem erros relevantes.',
    'Consegui preparar recheios e coberturas com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S171', frases: [
    'Não consegui decorar sobremesas e bolos de forma correta, precisei de ajuda constante.',
    'Consegui decorar sobremesas e bolos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui decorar sobremesas e bolos corretamente, sem erros relevantes.',
    'Consegui decorar sobremesas e bolos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S180', frases: [
    'Não consegui preparar e amassar massa de pão de forma correta, precisei de ajuda constante.',
    'Consegui preparar e amassar massa de pão, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preparar e amassar massa de pão corretamente, sem erros relevantes.',
    'Consegui preparar e amassar massa de pão com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S181', frases: [
    'Não consegui fermentar massa de forma correta, precisei de ajuda constante.',
    'Consegui fermentar massa, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui fermentar massa corretamente, sem erros relevantes.',
    'Consegui fermentar massa com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S182', frases: [
    'Não consegui moldar e cozer pão de forma correta, precisei de ajuda constante.',
    'Consegui moldar e cozer pão, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui moldar e cozer pão corretamente, sem erros relevantes.',
    'Consegui moldar e cozer pão com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S183', frases: [
    'Não consegui produzir massas especiais de panificação de forma correta, precisei de ajuda constante.',
    'Consegui produzir massas especiais de panificação, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui produzir massas especiais de panificação corretamente, sem erros relevantes.',
    'Consegui produzir massas especiais de panificação com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S190', frases: [
    'Não consegui empratar de forma correta, precisei de ajuda constante.',
    'Consegui empratar, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui empratar corretamente, sem erros relevantes.',
    'Consegui empratar com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S191', frases: [
    'Não consegui decorar prato de forma correta, precisei de ajuda constante.',
    'Consegui decorar prato, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui decorar prato corretamente, sem erros relevantes.',
    'Consegui decorar prato com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S192', frases: [
    'Não consegui organizar o passe e articular com a sala de forma correta, precisei de ajuda constante.',
    'Consegui organizar o passe e articular com a sala, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui organizar o passe e articular com a sala corretamente, sem erros relevantes.',
    'Consegui organizar o passe e articular com a sala com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S193', frases: [
    'Não consegui executar serviço à la minute de forma correta, precisei de ajuda constante.',
    'Consegui executar serviço à la minute, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui executar serviço à la minute corretamente, sem erros relevantes.',
    'Consegui executar serviço à la minute com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S194', frases: [
    'Não consegui manter alimentos em temperatura de serviço de forma correta, precisei de ajuda constante.',
    'Consegui manter alimentos em temperatura de serviço, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui manter alimentos em temperatura de serviço corretamente, sem erros relevantes.',
    'Consegui manter alimentos em temperatura de serviço com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S200', frases: [
    'Não consegui lavar as mãos corretamente de forma correta, precisei de ajuda constante.',
    'Consegui lavar as mãos corretamente, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui lavar as mãos corretamente corretamente, sem erros relevantes.',
    'Consegui lavar as mãos corretamente com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S201', frases: [
    'Não consegui utilizar touca e EPI de forma correta, precisei de ajuda constante.',
    'Consegui utilizar touca e EPI, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui utilizar touca e EPI corretamente, sem erros relevantes.',
    'Consegui utilizar touca e EPI com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S202', frases: [
    'Não consegui higienizar bancada, equipamentos e utensílios de forma correta, precisei de ajuda constante.',
    'Consegui higienizar bancada, equipamentos e utensílios, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui higienizar bancada, equipamentos e utensílios corretamente, sem erros relevantes.',
    'Consegui higienizar bancada, equipamentos e utensílios com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S203', frases: [
    'Não consegui registar temperaturas de forma correta, precisei de ajuda constante.',
    'Consegui registar temperaturas, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui registar temperaturas corretamente, sem erros relevantes.',
    'Consegui registar temperaturas com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S204', frases: [
    'Não consegui preencher registos HACCP de forma correta, precisei de ajuda constante.',
    'Consegui preencher registos HACCP, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui preencher registos HACCP corretamente, sem erros relevantes.',
    'Consegui preencher registos HACCP com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S205', frases: [
    'Não consegui identificar não conformidades e aplicar medidas corretivas de forma correta, precisei de ajuda constante.',
    'Consegui identificar não conformidades e aplicar medidas corretivas, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui identificar não conformidades e aplicar medidas corretivas corretamente, sem erros relevantes.',
    'Consegui identificar não conformidades e aplicar medidas corretivas com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S206', frases: [
    'Não consegui controlar a contaminação cruzada de forma correta, precisei de ajuda constante.',
    'Consegui controlar a contaminação cruzada, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui controlar a contaminação cruzada corretamente, sem erros relevantes.',
    'Consegui controlar a contaminação cruzada com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S210', frases: [
    'Não consegui separar resíduos de forma correta, precisei de ajuda constante.',
    'Consegui separar resíduos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui separar resíduos corretamente, sem erros relevantes.',
    'Consegui separar resíduos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S211', frases: [
    'Não consegui reduzir desperdício e aproveitar subprodutos de forma correta, precisei de ajuda constante.',
    'Consegui reduzir desperdício e aproveitar subprodutos, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui reduzir desperdício e aproveitar subprodutos corretamente, sem erros relevantes.',
    'Consegui reduzir desperdício e aproveitar subprodutos com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S212', frases: [
    'Não consegui aplicar princípios de economia circular de forma correta, precisei de ajuda constante.',
    'Consegui aplicar princípios de economia circular, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui aplicar princípios de economia circular corretamente, sem erros relevantes.',
    'Consegui aplicar princípios de economia circular com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
  { competenciaId: 'S213', frases: [
    'Não consegui gerir consumos de água e energia de forma correta, precisei de ajuda constante.',
    'Consegui gerir consumos de água e energia, mas com algumas dificuldades ou erros que precisaram de correção.',
    'Consegui gerir consumos de água e energia corretamente, sem erros relevantes.',
    'Consegui gerir consumos de água e energia com autonomia e rigor, e ainda ajudei colegas que tiveram dificuldades.',
  ] },
];
